// 游戏分类定义
const categories = {
    action: {
        id: 'action',
        name: '动作游戏',
        icon: '<i class="fas fa-gamepad"></i>',
        keywords: ['action', 'fight', 'battle', 'run', 'jump', 'shooter']
    },
    adventure: {
        id: 'adventure',
        name: '冒险游戏',
        icon: '<i class="fas fa-compass"></i>',
        keywords: ['adventure', 'explore', 'quest', 'journey', 'story']
    },
    puzzle: {
        id: 'puzzle',
        name: '益智游戏',
        icon: '<i class="fas fa-puzzle-piece"></i>',
        keywords: ['puzzle', 'brain', 'logic', 'match', 'solve', 'think']
    },
    strategy: {
        id: 'strategy',
        name: '策略游戏',
        icon: '<i class="fas fa-chess"></i>',
        keywords: ['strategy', 'build', 'manage', 'plan', 'tower']
    },
    sports: {
        id: 'sports',
        name: '体育游戏',
        icon: '<i class="fas fa-futbol"></i>',
        keywords: ['sports', 'ball', 'race', 'soccer', 'basketball']
    },
    racing: {
        id: 'racing',
        name: '赛车游戏',
        icon: '<i class="fas fa-car"></i>',
        keywords: ['racing', 'car', 'drive', 'speed', 'vehicle']
    },
    shooting: {
        id: 'shooting',
        name: '射击游戏',
        icon: '<i class="fas fa-crosshairs"></i>',
        keywords: ['shooting', 'gun', 'sniper', 'aim', 'target']
    },
    casual: {
        id: 'casual',
        name: '休闲游戏',
        icon: '<i class="fas fa-smile"></i>',
        keywords: ['casual', 'simple', 'relax', 'easy', 'fun']
    },
    multiplayer: {
        id: 'multiplayer',
        name: '多人游戏',
        icon: '<i class="fas fa-users"></i>',
        keywords: ['multiplayer', 'cooperative', 'competitive', 'social']
    }
};

// 自动分类函数
function autoCategorizegame(game) {
    // 基于游戏标题、描述和标签进行分类
    const gameText = `${game.title} ${game.description} ${game.tags.join(' ')} ${game.subCategory || ''}`.toLowerCase();
    
    // 记录每个分类的匹配分数
    const scores = {};
    
    // 计算每个分类的匹配度
    Object.entries(categories).forEach(([categoryId, category]) => {
        // 基础分数
        let score = category.keywords.reduce((total, keyword) => {
            const regex = new RegExp(keyword, 'gi');
            const matches = (gameText.match(regex) || []).length;
            return total + matches;
        }, 0);
        
        // 额外规则
        if (game.subCategory) {
            // 子分类匹配加分
            if (category.keywords.some(keyword => game.subCategory.toLowerCase().includes(keyword))) {
                score += 2;
            }
        }
        
        // 特定类型判断
        if (categoryId === 'action' && gameText.includes('combat')) score += 1;
        if (categoryId === 'puzzle' && gameText.includes('solve')) score += 1;
        if (categoryId === 'strategy' && gameText.includes('manage')) score += 1;
        if (categoryId === 'casual' && gameText.includes('relax')) score += 1;
        
        scores[categoryId] = score;
    });
    
    // 找出匹配度最高的分类
    const bestMatch = Object.entries(scores).reduce((best, [categoryId, score]) => {
        return score > best.score ? { categoryId, score } : best;
    }, { categoryId: 'casual', score: 0 });
    
    return bestMatch.score > 0 ? bestMatch.categoryId : 'casual';
}

// 游戏数据
const gameData = [
    // 新添加的游戏
    {
        id: 'giant-attack',
        title: 'Giant Attack',
        category: 'action',
        image: 'img/Giant Attack.jpg',
        url: 'https://play.famobi.com/giant-attack',
        description: '指挥你的巨人军队，击败敌人，摧毁城堡和建筑。这款动作游戏充满了破坏与策略。',
        rating: 4.6,
        releaseDate: '2023-10-12',
        playCount: 175000,
        isNew: true,
        features: ['多种关卡', '不同类型的巨人', '策略性破坏'],
        tags: ['action', 'strategy', 'destruction']
    },
    {
        id: 'crazy-hen-level',
        title: 'Crazy Hen Level',
        category: 'action',
        image: 'img/Crazy Hen Level.jpg',
        url: 'https://play.famobi.com/crazy-hen-level',
        description: '帮助疯狂的母鸡在各种关卡中奔跑并收集鸡蛋。躲避障碍物，使用特殊能力，完成挑战。',
        rating: 4.3,
        releaseDate: '2023-11-05',
        playCount: 143000,
        isNew: true,
        features: ['多样关卡', '特殊能力', '收集元素'],
        tags: ['action', 'run', 'collect']
    },
    {
        id: 'good-shelves',
        title: 'Good Shelves',
        category: 'puzzle',
        image: 'img/Good Shelves.jpg',
        url: 'https://play.famobi.com/good-shelves',
        description: '整理和组织各种物品到书架上。在这款益智游戏中，你需要根据颜色和形状合理分类物品。',
        rating: 4.5,
        releaseDate: '2023-09-20',
        playCount: 92000,
        isNew: true,
        features: ['逻辑思考', '空间排列', '渐进难度'],
        tags: ['puzzle', 'organization', 'sorting']
    },
    {
        id: 'dance-battle',
        title: 'Dance Battle',
        category: 'casual',
        image: 'img/Dance Battle.jpg',
        url: 'https://play.famobi.com/dance-battle',
        description: '在这款节奏游戏中展示你的舞蹈技巧，按照屏幕提示完成各种舞步，击败对手成为舞蹈之王。',
        rating: 4.4,
        releaseDate: '2023-08-15',
        playCount: 167000,
        isNew: true,
        features: ['动感音乐', '多种舞步', '竞争模式'],
        tags: ['casual', 'rhythm', 'dance']
    },
    {
        id: 'tile-journey',
        title: 'Tile Journey',
        category: 'puzzle',
        image: 'img/Tile Journey.jpg',
        url: 'https://play.famobi.com/tile-journey',
        description: '在这款拼图游戏中，移动和旋转瓷砖创建完整的路径。帮助角色到达目的地，解锁新的挑战。',
        rating: 4.7,
        releaseDate: '2023-07-28',
        playCount: 132000,
        isNew: false,
        features: ['丰富关卡', '递增难度', '独特解谜机制'],
        tags: ['puzzle', 'path', 'logic']
    },
    {
        id: 'love-tester',
        title: 'Love Tester',
        category: 'casual',
        image: 'img/Love Tester.jpg',
        url: 'https://play.famobi.com/love-tester',
        description: '测试你与朋友或名人之间的爱情兼容性。输入名字，看看你们的爱情得分。一款有趣的休闲游戏。',
        rating: 4.2,
        releaseDate: '2023-02-14',
        playCount: 220000,
        isNew: false,
        features: ['趣味计算', '分享结果', '多种测试方式'],
        tags: ['casual', 'fun', 'social']
    },
    {
        id: 'emoji-match',
        title: 'Emoji Match',
        category: 'puzzle',
        image: 'img/Emoji Match.jpg',
        url: 'https://play.famobi.com/emoji-match',
        description: '连接相同的emoji表情，创建匹配组合以消除它们。这款经典的三消游戏使用现代表情符号，富有趣味。',
        rating: 4.5,
        releaseDate: '2023-06-01',
        playCount: 158000,
        isNew: false,
        features: ['丰富表情', '多样关卡', '特殊道具'],
        tags: ['puzzle', 'match3', 'emoji']
    },
    {
        id: 'tower-smash',
        title: 'Tower Smash',
        category: 'action',
        image: 'img/Tower Smash.jpg',
        url: 'https://play.famobi.com/tower-smash',
        description: '摧毁高塔，让它倒塌的方式越壮观越好。计算最佳的撞击点，引发连锁反应，获取最高分数。',
        rating: 4.6,
        releaseDate: '2023-05-15',
        playCount: 178000,
        isNew: false,
        features: ['物理引擎', '不同类型建筑', '连锁反应'],
        tags: ['action', 'destruction', 'physics']
    },
    {
        id: 'tower-smash-level',
        title: 'Tower Smash Level',
        category: 'action',
        image: 'img/Tower Smash Level.jpg',
        url: 'https://play.famobi.com/tower-smash-level',
        description: 'Tower Smash的进阶版本，包含更多关卡挑战。精确计算你的撞击点，最大化破坏效果。',
        rating: 4.5,
        releaseDate: '2023-07-10',
        playCount: 145000,
        isNew: false,
        features: ['多样关卡', '升级系统', '成就解锁'],
        tags: ['action', 'destruction', 'physics']
    },
    {
        id: 'save-the-princess',
        title: 'Save the Princess',
        category: 'adventure',
        image: 'img/Save the Princess.jpg',
        url: 'https://play.famobi.com/save-the-princess',
        description: '在这款冒险游戏中，解决各种谜题，战胜怪物，最终拯救被困在塔中的公主。',
        rating: 4.4,
        releaseDate: '2023-04-20',
        playCount: 125000,
        isNew: false,
        features: ['引人入胜的故事', '多样谜题', '角色升级'],
        tags: ['adventure', 'puzzle', 'story']
    },
    {
        id: 'peet-a-lock',
        title: 'Peet a Lock',
        category: 'puzzle',
        image: 'img/Peet a Lock.jpg',
        url: 'https://play.famobi.com/peet-a-lock',
        description: '解开各种锁的谜题，考验你的观察力和逻辑思维。每个锁都有不同的解锁机制。',
        rating: 4.3,
        releaseDate: '2023-03-12',
        playCount: 89000,
        isNew: false,
        features: ['独特谜题', '渐进难度', '大脑挑战'],
        tags: ['puzzle', 'logic', 'observation']
    },
    {
        id: 'peet-around',
        title: 'Peet Around',
        category: 'action',
        image: 'img/Peet Around.jpg',
        url: 'https://play.famobi.com/peet-around',
        description: '控制角色探索各种环境，收集物品，避开敌人。敏捷性和战略思维在这个游戏中至关重要。',
        rating: 4.5,
        releaseDate: '2023-06-22',
        playCount: 112000,
        isNew: false,
        features: ['开放探索', '收集元素', '隐藏关卡'],
        tags: ['action', 'adventure', 'explore']
    },
    {
        id: 'pengu-slide',
        title: 'Pengu Slide',
        category: 'action',
        image: 'img/Pengu Slide.jpg',
        url: 'https://play.famobi.com/pengu-slide',
        description: '帮助可爱的企鹅在冰面上滑行，收集鱼和其他物品，避开障碍物。控制滑行方向和速度是关键。',
        rating: 4.6,
        releaseDate: '2023-01-18',
        playCount: 193000,
        isNew: false,
        features: ['冰雪场景', '物理滑行', '关卡多样性'],
        tags: ['action', 'casual', 'winter']
    },
    {
        id: 'words-of-wonders',
        title: 'Words of Wonders',
        category: 'puzzle',
        image: 'img/Words of Wonders.jpg',
        url: 'https://play.famobi.com/words-of-wonders',
        description: '在这款文字益智游戏中，连接字母形成单词，解锁世界各地的著名景点。提升你的词汇量和解谜能力。',
        rating: 4.7,
        releaseDate: '2023-02-05',
        playCount: 210000,
        isNew: false,
        features: ['丰富词汇', '世界景点', '渐进难度'],
        tags: ['puzzle', 'word', 'educational']
    },
    {
        id: 'emoji-flow',
        title: 'Emoji Flow',
        category: 'puzzle',
        image: 'img/Emoji Flow.jpg',
        url: 'https://play.famobi.com/emoji-flow',
        description: '连接相同颜色的表情符号，创建流畅的路径。这款益智游戏考验你的空间思维和策略规划能力。',
        rating: 4.3,
        releaseDate: '2023-05-30',
        playCount: 135000,
        isNew: false,
        features: ['多色谜题', '流畅操作', '无限关卡'],
        tags: ['puzzle', 'flow', 'emoji']
    },
    {
        id: 'neon-swing',
        title: 'Neon Swing',
        category: 'action',
        image: 'img/Neon Swing.jpg',
        url: 'https://play.famobi.com/neon-swing',
        description: '在这款霓虹风格的游戏中，控制角色在建筑物之间摆动。精确的时间掌握和反应能力是成功的关键。',
        rating: 4.5,
        releaseDate: '2023-08-03',
        playCount: 168000,
        isNew: true,
        features: ['霓虹视觉风格', '物理摆动', '技能提升'],
        tags: ['action', 'arcade', 'neon']
    },
    {
        id: 'neon-tower',
        title: 'Neon Tower',
        category: 'action',
        image: 'img/Neon Tower.jpg',
        url: 'https://play.famobi.com/neon-tower',
        description: '在闪烁的霓虹塔中攀爬，避开障碍物，收集能量。这款动作游戏具有独特的视觉风格和挑战性玩法。',
        rating: 4.4,
        releaseDate: '2023-09-07',
        playCount: 142000,
        isNew: true,
        features: ['炫目视觉', '技能挑战', '垂直攀爬'],
        tags: ['action', 'climb', 'neon']
    },
    {
        id: 'drift-dudes',
        title: 'Drift Dudes',
        category: 'racing',
        image: 'img/Drift Dudes.jpg',
        url: 'https://play.famobi.com/drift-dudes',
        description: '在各种赛道上展示你的漂移技巧。控制车辆，完成漂移挑战，解锁新车和赛道。',
        rating: 4.6,
        releaseDate: '2023-07-15',
        playCount: 185000,
        isNew: false,
        features: ['多种赛车', '不同赛道', '漂移物理'],
        tags: ['racing', 'drift', 'cars']
    },
    {
        id: 'slope',
        title: 'Slope',
        category: 'action',
        image: 'img/Slope.jpg',
        url: 'https://play.famobi.com/slope',
        description: '控制球体在危险的斜坡上滚动。避开障碍物，保持平衡，看看你能滚多远。这款游戏考验你的反应速度和控制能力。',
        rating: 4.8,
        releaseDate: '2023-03-25',
        playCount: 250000,
        isNew: false,
        features: ['无尽模式', '速度挑战', '简单操作'],
        tags: ['action', 'reflex', 'endless']
    },
    {
        id: 'cubito',
        title: 'Cubito',
        category: 'puzzle',
        image: 'img/Cubito.jpg',
        url: 'https://play.famobi.com/cubito',
        description: '移动立方体到指定位置，解决空间谜题。这款3D益智游戏考验你的空间想象力和逻辑思维。',
        rating: 4.5,
        releaseDate: '2023-04-10',
        playCount: 115000,
        isNew: false,
        features: ['3D谜题', '递增难度', '空间思维'],
        tags: ['puzzle', '3d', 'logic']
    },
    {
        id: 'tap-tap-dunk',
        title: 'Tap Tap Dunk',
        category: 'sports',
        image: 'img/Tap Tap Dunk.jpg',
        url: 'https://play.famobi.com/tap-tap-dunk',
        description: '通过精确的点击时机投篮得分。挑战自己，创造最高记录，解锁不同的球和特效。',
        rating: 4.4,
        releaseDate: '2023-06-12',
        playCount: 178000,
        isNew: false,
        features: ['简单操作', '技能提升', '视觉特效'],
        tags: ['sports', 'basketball', 'tap']
    },
    {
        id: 'ramp',
        title: 'Ramp',
        category: 'racing',
        image: 'img/Ramp.jpg',
        url: 'https://play.famobi.com/ramp',
        description: '驾驶车辆跳跃各种坡道，执行特技动作，争取最高分数。物理效果真实，操作简单上手。',
        rating: 4.6,
        releaseDate: '2023-05-20',
        playCount: 165000,
        isNew: false,
        features: ['物理引擎', '多种车辆', '特技动作'],
        tags: ['racing', 'stunt', 'physics']
    },
    {
        id: 'diamond-rush',
        title: 'Diamond Rush',
        category: 'puzzle',
        image: 'img/Diamond Rush.jpg',
        url: 'https://play.famobi.com/diamond-rush',
        description: '收集闪亮的钻石，避开障碍物和敌人。这款益智冒险游戏结合了策略和时机掌握。',
        rating: 4.5,
        releaseDate: '2023-07-08',
        playCount: 145000,
        isNew: false,
        features: ['丰富关卡', '宝藏收集', '解谜元素'],
        tags: ['puzzle', 'adventure', 'collect']
    },
    {
        id: 'color-tunnel',
        title: 'Color Tunnel',
        category: 'action',
        image: 'img/Color Tunnel.jpg',
        url: 'https://play.famobi.com/color-tunnel',
        description: '在变换颜色的隧道中穿行，匹配你的颜色与隧道壁来避免碰撞。这款游戏考验你的反应能力和颜色匹配速度。',
        rating: 4.7,
        releaseDate: '2023-02-28',
        playCount: 198000,
        isNew: false,
        features: ['炫彩视觉', '快速反应', '节奏感'],
        tags: ['action', 'reflex', 'color']
    },
    {
        id: 'butterfly-shimai',
        title: 'Butterfly Shimai',
        category: 'casual',
        image: 'img/Butterfly Shimai.jpg',
        url: 'https://play.famobi.com/butterfly-shimai',
        description: '在这款休闲游戏中，帮助蝴蝶收集花蜜，避开蜘蛛网和其他危险。享受美丽的花园场景和轻松的游戏体验。',
        rating: 4.3,
        releaseDate: '2023-04-15',
        playCount: 120000,
        isNew: false,
        features: ['精美画面', '简单控制', '放松体验'],
        tags: ['casual', 'butterfly', 'nature']
    },
    {
        id: 'e-scooter',
        title: 'E-Scooter',
        category: 'racing',
        image: 'img/E-Scooter.jpg',
        url: 'https://play.famobi.com/e-scooter',
        description: '骑电动滑板车穿越城市，执行特技动作，收集金币。这款赛车游戏有现代城市背景和流畅的控制。',
        rating: 4.4,
        releaseDate: '2023-08-22',
        playCount: 132000,
        isNew: true,
        features: ['城市环境', '特技动作', '升级系统'],
        tags: ['racing', 'scooter', 'urban']
    },
    {
        id: 'pop-it-duel',
        title: 'Pop It Duel',
        category: 'casual',
        image: 'img/Pop It Duel.jpg',
        url: 'https://play.famobi.com/pop-it-duel',
        description: '在这款休闲游戏中，与对手对决戳泡泡。策略性地选择你的行动，成为泡泡大师。',
        rating: 4.2,
        releaseDate: '2023-09-10',
        playCount: 155000,
        isNew: true,
        features: ['双人对战', '策略思考', '多彩设计'],
        tags: ['casual', 'duel', 'strategy']
    },
    {
        id: 'stair-race',
        title: 'Stair Race',
        category: 'action',
        image: 'img/Stair Race.jpg',
        url: 'https://play.famobi.com/stair-race',
        description: '在这款竞速游戏中，控制角色快速上楼梯，避开障碍物，超越对手到达终点。',
        rating: 4.5,
        releaseDate: '2023-10-05',
        playCount: 143000,
        isNew: true,
        features: ['多人竞速', '角色解锁', '技能提升'],
        tags: ['action', 'race', 'climb']
    },
    {
        id: 'crowd-run',
        title: 'Crowd Run',
        category: 'action',
        image: 'img/Crowd Run.jpg',
        url: 'https://play.famobi.com/crowd-run',
        description: '控制一群人穿越障碍赛道。收集更多的人加入你的队伍，成功通过各种挑战。',
        rating: 4.6,
        releaseDate: '2023-11-08',
        playCount: 165000,
        isNew: true,
        features: ['人群控制', '多样障碍', '策略思考'],
        tags: ['action', 'crowd', 'run']
    },
    {
        id: 'uncle-ahmed',
        title: 'Uncle Ahmed',
        category: 'adventure',
        image: 'img/Uncle Ahmed.jpg',
        url: 'https://play.famobi.com/uncle-ahmed',
        description: '在这款冒险游戏中，跟随艾哈迈德叔叔探索古代遗迹，解开谜题，寻找宝藏。',
        rating: 4.4,
        releaseDate: '2023-10-20',
        playCount: 98000,
        isNew: true,
        features: ['探索元素', '谜题解决', '故事情节'],
        tags: ['adventure', 'puzzle', 'explore']
    },
    {
        id: 'dices',
        title: 'Dices',
        category: 'casual',
        image: 'img/Dices.jpg',
        url: 'https://play.famobi.com/dices',
        description: '在这款经典骰子游戏中测试你的运气。不同的游戏模式和规则带来多样的游戏体验。',
        rating: 4.1,
        releaseDate: '2023-03-18',
        playCount: 110000,
        isNew: false,
        features: ['多种玩法', '经典规则', '运气挑战'],
        tags: ['casual', 'dice', 'classic']
    },
    {
        id: 'frankenstein-go',
        title: 'Frankenstein Go',
        category: 'action',
        image: 'img/Frankenstein Go.jpg',
        url: 'https://play.famobi.com/frankenstein-go',
        description: '帮助弗兰肯斯坦的怪物逃离愤怒的村民，收集能量，穿越各种环境。',
        rating: 4.3,
        releaseDate: '2023-10-31',
        playCount: 87000,
        isNew: true,
        features: ['哥特风格', '跑酷元素', '能力升级'],
        tags: ['action', 'horror', 'run']
    },
    {
        id: 'om-nom-connect-classic',
        title: 'Om Nom Connect Classic',
        category: 'puzzle',
        image: 'img/Om Nom Connect Classic.jpg',
        url: 'https://play.famobi.com/om-nom-connect-classic',
        description: '连接相同颜色的线条，帮助小怪物吃到糖果。这款经典益智游戏考验你的策略思维。',
        rating: 4.6,
        releaseDate: '2023-06-15',
        playCount: 175000,
        isNew: false,
        features: ['可爱角色', '递增难度', '路径谜题'],
        tags: ['puzzle', 'connect', 'cute']
    },
    {
        id: 'om-nom-bubbles',
        title: 'Om Nom Bubbles',
        category: 'puzzle',
        image: 'img/Om Nom Bubbles.jpg',
        url: 'https://play.famobi.com/om-nom-bubbles',
        description: '发射彩色泡泡，匹配三个或更多相同颜色的泡泡以消除它们。帮助小怪物吃到所有的糖果。',
        rating: 4.5,
        releaseDate: '2023-07-22',
        playCount: 156000,
        isNew: false,
        features: ['经典玩法', '可爱角色', '多样关卡'],
        tags: ['puzzle', 'bubble', 'match3']
    },
    {
        id: 'pop-it',
        title: 'Pop It',
        category: 'casual',
        image: 'img/Pop It.jpg',
        url: 'https://play.famobi.com/pop-it',
        description: '在这款放松的游戏中，戳破所有的泡泡，体验解压感。不同形状和颜色的泡泡带来多样的体验。',
        rating: 4.2,
        releaseDate: '2023-08-08',
        playCount: 190000,
        isNew: true,
        features: ['多彩设计', '解压体验', '简单操作'],
        tags: ['casual', 'relaxing', 'popping']
    },
    {
        id: 'traffic-tom',
        title: 'Traffic Tom',
        category: 'strategy',
        image: 'img/Traffic Tom.jpg',
        url: 'https://play.famobi.com/traffic-tom',
        description: '控制交通信号灯，确保车辆安全通过交叉路口。这款策略游戏考验你的时间管理和决策能力。',
        rating: 4.4,
        releaseDate: '2023-05-12',
        playCount: 125000,
        isNew: false,
        features: ['城市场景', '策略思维', '渐进难度'],
        tags: ['strategy', 'traffic', 'management']
    },
    {
        id: 'onet-gallery',
        title: 'Onet Gallery',
        category: 'puzzle',
        image: 'img/Onet Gallery.jpg',
        url: 'https://play.famobi.com/onet-gallery',
        description: '匹配相同的图像，通过最少的三个转弯连接它们。这款经典连连看游戏有美丽的图片和渐进的难度。',
        rating: 4.6,
        releaseDate: '2023-04-25',
        playCount: 145000,
        isNew: false,
        features: ['精美图片', '多种主题', '大脑挑战'],
        tags: ['puzzle', 'matching', 'gallery']
    },
    {
        id: 'om-nom-run',
        title: 'Om Nom Run',
        category: 'action',
        image: 'img/Om Nom Run.jpg',
        url: 'https://play.famobi.com/om-nom-run',
        description: '帮助可爱的小怪物奔跑，收集糖果，避开障碍物。这款无尽跑酷游戏充满了欢乐和挑战。',
        rating: 4.7,
        releaseDate: '2023-09-03',
        playCount: 188000,
        isNew: true,
        features: ['可爱角色', '特殊能力', '收集元素'],
        tags: ['action', 'run', 'cute']
    },
    {
        id: 'euro-penalty-cup',
        title: 'Euro Penalty Cup',
        category: 'sports',
        image: 'img/Euro Penalty Cup.jpg',
        url: 'https://play.famobi.com/euro-penalty-cup',
        description: '参加欧洲杯点球大战，展示你的射门和守门技巧。代表你的国家赢得冠军。',
        rating: 4.5,
        releaseDate: '2023-06-10',
        playCount: 167000,
        isNew: false,
        features: ['多国队伍', '真实物理', '锦标赛模式'],
        tags: ['sports', 'soccer', 'penalty']
    },
    {
        id: 'train',
        title: 'Train',
        category: 'strategy',
        image: 'img/Train.jpg',
        url: 'https://play.famobi.com/train',
        description: '建造和管理你的铁路网络。连接城市，运送乘客和货物，扩展你的铁路帝国。',
        rating: 4.6,
        releaseDate: '2023-07-30',
        playCount: 134000,
        isNew: false,
        features: ['城市建设', '资源管理', '策略规划'],
        tags: ['strategy', 'train', 'management']
    },
    {
        id: 'giant',
        title: 'Giant',
        category: 'action',
        image: 'img/Giant.jpg',
        url: 'https://play.famobi.com/giant',
        description: '控制巨人，摧毁城市建筑物，应对军队的攻击。这款破坏游戏让你体验成为无敌巨人的快感。',
        rating: 4.5,
        releaseDate: '2023-08-15',
        playCount: 154000,
        isNew: true,
        features: ['城市破坏', '力量升级', '多种能力'],
        tags: ['action', 'destruction', 'giant']
    },
    {
        id: 'fuzzies',
        title: 'Fuzzies',
        category: 'puzzle',
        image: 'img/Fuzzies.jpg',
        url: 'https://play.famobi.com/fuzzies',
        description: '连接相同颜色的毛球，创建闭合的路径。这款益智游戏考验你的空间思维和战略规划能力。',
        rating: 4.4,
        releaseDate: '2023-05-28',
        playCount: 123000,
        isNew: false,
        features: ['多彩谜题', '递增难度', '无限关卡'],
        tags: ['puzzle', 'connect', 'color']
    },
    {
        id: 'garden-bloom',
        title: 'Garden Bloom',
        category: 'puzzle',
        image: 'img/Garden Bloom.jpg',
        url: 'https://play.famobi.com/garden-bloom',
        description: '帮助花园中的植物开花，通过解决拼图和匹配颜色。这款放松的益智游戏有美丽的园艺主题。',
        rating: 4.3,
        releaseDate: '2023-04-05',
        playCount: 137000,
        isNew: false,
        features: ['花园主题', '拼图元素', '放松体验'],
        tags: ['puzzle', 'garden', 'bloom']
    },
    {
        id: 'brain-trainer',
        title: 'Brain Trainer',
        category: 'puzzle',
        image: 'img/Brain Trainer.jpg',
        url: 'https://play.famobi.com/brain-trainer',
        description: '通过各种迷你游戏和挑战训练你的大脑。提高记忆力、注意力和问题解决能力。',
        rating: 4.6,
        releaseDate: '2023-03-20',
        playCount: 165000,
        isNew: false,
        features: ['多样挑战', '认知训练', '进度跟踪'],
        tags: ['puzzle', 'brain', 'educational']
    },
    {
        id: 'garden-match',
        title: 'Garden Match',
        category: 'puzzle',
        image: 'img/Garden Match.jpg',
        url: 'https://play.famobi.com/garden-match',
        description: '在美丽的花园环境中，匹配相同的植物和花卉。这款三消游戏结合了休闲玩法和园艺主题。',
        rating: 4.5,
        releaseDate: '2023-05-15',
        playCount: 148000,
        isNew: false,
        features: ['园艺主题', '多样关卡', '特殊道具'],
        tags: ['puzzle', 'match3', 'garden']
    },
    {
        id: 'pull-pins',
        title: 'Pull Pins',
        category: 'puzzle',
        image: 'img/Pull Pins.jpg',
        url: 'https://play.famobi.com/pull-pins',
        description: '拔出正确的销子，让球体通过迷宫到达目标位置。这款物理益智游戏需要战略思考和规划。',
        rating: 4.7,
        releaseDate: '2023-10-10',
        playCount: 192000,
        isNew: true,
        features: ['物理谜题', '渐进难度', '战略思考'],
        tags: ['puzzle', 'physics', 'pins']
    },
    {
        id: 'rise-up',
        title: 'Rise Up',
        category: 'casual',
        image: 'img/Rise Up.jpg',
        url: 'https://play.famobi.com/rise-up',
        description: '在这款简单而富有挑战性的游戏中，保护气球安全上升，避开各种障碍物。需要精确控制和快速反应。',
        rating: 4.7,
        releaseDate: '2023-12-05',
        playCount: 230000,
        isNew: true,
        features: ['简单操作', '递增难度', '独特美术风格'],
        tags: ['casual', 'action', 'reflex']
    },
    {
        id: 'giant-rush',
        title: 'Giant Rush',
        category: 'action',
        image: 'img/Giant Rush.jpg',
        url: 'https://play.famobi.com/giant-rush',
        description: '不断奔跑并收集资源，让你的角色变得更加强大。躲避障碍物并击败敌人，成为终极巨人。',
        rating: 4.6,
        releaseDate: '2023-11-15',
        playCount: 185000,
        isNew: true,
        features: ['角色升级', '快节奏游戏', '收集元素'],
        tags: ['action', 'run', 'collect']
    },
    {
        id: 'train-miner',
        title: 'Train Miner',
        category: 'strategy',
        image: 'img/Train Miner.jpg',
        url: 'https://play.famobi.com/train-miner',
        description: '驾驶你的采矿火车，开采资源，升级装备，扩展铁路网络。在这款策略管理游戏中建立自己的矿业帝国。',
        rating: 4.5,
        releaseDate: '2023-10-20',
        playCount: 120000,
        isNew: true,
        features: ['资源管理', '建造系统', '升级机制'],
        tags: ['strategy', 'build', 'manage']
    },
    {
        id: 'western-sniper',
        title: 'Western Sniper',
        category: 'shooting',
        image: 'img/Western Sniper.jpg',
        url: 'https://play.famobi.com/western-sniper',
        description: '在狂野西部背景下，成为一名神枪手，完成各种狙击任务。测试你的瞄准技巧和耐心。',
        rating: 4.4,
        releaseDate: '2023-09-30',
        playCount: 95000,
        isNew: true,
        features: ['西部场景', '精准射击', '多样任务'],
        tags: ['shooting', 'sniper', 'aim']
    },
    {
        id: 'go-escape',
        title: 'Go Escape',
        category: 'adventure',
        image: 'img/Go Escape.jpg',
        url: 'https://play.famobi.com/go-escape',
        description: '解开谜题，找到线索，逃离各种奇怪的房间。在这款冒险解谜游戏中考验你的智慧和观察力。',
        rating: 4.3,
        releaseDate: '2023-08-25',
        playCount: 88000,
        isNew: true,
        features: ['密室逃脱', '解谜元素', '情境多变'],
        tags: ['adventure', 'puzzle', 'escape']
    },
    {
        id: 'color-fill',
        title: 'Color Fill',
        category: 'puzzle',
        image: 'img/Color Fill.jpg',
        url: 'https://play.famobi.com/color-fill',
        description: '用颜色填充空白区域，避开障碍物和敌人。这款益智游戏需要策略思考和计划能力。',
        rating: 4.5,
        releaseDate: '2023-07-18',
        playCount: 105000,
        isNew: false,
        features: ['多彩关卡', '渐进难度', '策略思考'],
        tags: ['puzzle', 'color', 'strategy']
    },
    {
        id: 'spot-the-cat',
        title: 'Spot the Cat',
        category: 'puzzle',
        image: 'img/Spot the Cat.jpg',
        url: 'https://play.famobi.com/spot-the-cat',
        description: '在复杂的图景中找出隐藏的猫咪。考验你的观察力和专注力，寻找那些狡猾的猫咪。',
        rating: 4.2,
        releaseDate: '2023-06-10',
        playCount: 75000,
        isNew: false,
        features: ['隐藏对象', '精美插图', '计时挑战'],
        tags: ['puzzle', 'hidden', 'observation']
    },
    {
        id: 'braindom',
        title: 'Braindom',
        category: 'puzzle',
        image: 'img/Braindom.jpg',
        url: 'https://play.famobi.com/braindom',
        description: '挑战你的思维能力，解决各种脑筋急转弯和益智谜题。每一关都有不同的解谜方式。',
        rating: 4.6,
        releaseDate: '2023-01-15',
        playCount: 135000,
        isNew: false,
        features: ['丰富的关卡', '创新玩法', '思维挑战'],
        tags: ['puzzle', 'brain', 'logic']
    },
    {
        id: 'sort-it',
        title: 'Sort It',
        category: 'puzzle',
        image: 'img/Sort It.jpg',
        url: 'https://play.famobi.com/sort-it',
        description: '将彩色液体按颜色分类排序，在有限的瓶子中完成分类挑战。需要策略思考和规划。',
        rating: 4.7,
        releaseDate: '2023-02-20',
        playCount: 182000,
        isNew: false,
        features: ['多样关卡', '渐进难度', '放松游戏体验'],
        tags: ['puzzle', 'sorting', 'strategy']
    },
    {
        id: 'cube-match',
        title: 'Cube Match',
        category: 'puzzle',
        image: 'img/Cube Match.jpg',
        url: 'https://play.famobi.com/cube-match',
        description: '匹配相同颜色的方块，消除它们并获得高分。经典的三消游戏玩法，加入了新的元素和挑战。',
        rating: 4.5,
        releaseDate: '2023-03-10',
        playCount: 98000,
        isNew: false,
        features: ['简单上手', '多种关卡', '特殊方块'],
        tags: ['puzzle', 'match3', 'casual']
    },
    {
        id: 'parking-jam',
        title: 'Parking Jam',
        category: 'puzzle',
        image: 'img/Parking Jam.jpg',
        url: 'https://play.famobi.com/parking-jam',
        description: '帮助汽车从拥挤的停车场驶出，通过移动其他车辆创建路径。考验你的空间思维和规划能力。',
        rating: 4.4,
        releaseDate: '2023-04-05',
        playCount: 76000,
        isNew: false,
        features: ['趣味关卡', '渐进难度', '休闲游戏体验'],
        tags: ['puzzle', 'cars', 'logic']
    },
    {
        id: 'fashion-battle',
        title: 'Fashion Battle',
        category: 'casual',
        image: 'img/Fashion Battle.jpg',
        url: 'https://play.famobi.com/fashion-battle',
        description: '展示你的时尚品味，与对手进行服装搭配比拼。选择最佳服装组合赢得时尚战斗。',
        rating: 4.3,
        releaseDate: '2023-05-18',
        playCount: 125000,
        isNew: false,
        features: ['时尚元素', '多样角色', '服装收集'],
        tags: ['casual', 'fashion', 'dress-up']
    },
    {
        id: 'fruit-party',
        title: 'Fruit Party',
        category: 'puzzle',
        image: 'img/Fruit Party.jpg',
        url: 'https://play.famobi.com/fruit-party',
        description: '将相同的水果配对消除，享受这款色彩缤纷的消除游戏。简单易上手，但充满挑战。',
        rating: 4.5,
        releaseDate: '2023-06-12',
        playCount: 145000,
        isNew: false,
        features: ['丰富关卡', '特殊水果', '连击奖励'],
        tags: ['puzzle', 'match3', 'fruits']
    },
    {
        id: 'thief-puzzle',
        title: 'Thief Puzzle',
        category: 'puzzle',
        image: 'img/Thief Puzzle.jpg',
        url: 'https://play.famobi.com/thief-puzzle',
        description: '帮助小偷解决各种谜题，找到宝藏并成功逃脱。每个关卡都有独特的解谜方式。',
        rating: 4.6,
        releaseDate: '2023-07-25',
        playCount: 89000,
        isNew: true,
        features: ['多样谜题', '故事情节', '创意解谜'],
        tags: ['puzzle', 'adventure', 'logic']
    },
    {
        id: 'guess-their-answer',
        title: 'Guess Their Answer',
        category: 'casual',
        image: 'img/Guess Their Answer.jpg',
        url: 'https://play.famobi.com/guess-their-answer',
        description: '猜测大多数人会如何回答各种问题。测试你对常识和大众心理的了解。',
        rating: 4.2,
        releaseDate: '2023-08-30',
        playCount: 68000,
        isNew: true,
        features: ['趣味问题', '社交元素', '有趣统计'],
        tags: ['casual', 'quiz', 'social']
    },
    {
        id: 'speed-master',
        title: 'Speed Master',
        category: 'action',
        image: 'img/Speed Master.jpg',
        url: 'https://play.famobi.com/speed-master',
        description: '测试你的反应速度和精准度，在这款快节奏游戏中击打出现的目标。随着游戏进行速度会越来越快。',
        rating: 4.7,
        releaseDate: '2023-09-15',
        playCount: 112000,
        isNew: true,
        features: ['反应挑战', '分数系统', '多种模式'],
        tags: ['action', 'reflex', 'speed']
    },
    {
        id: 'alien-attack',
        title: 'Alien Attack',
        category: 'shooting',
        image: 'img/Alien Attack.jpg',
        url: 'https://play.famobi.com/alien-attack',
        description: '在这款经典射击游戏中抵御外星人入侵，保卫地球免受威胁。升级武器并摧毁敌人的飞船。',
        rating: 4.8,
        releaseDate: '2023-10-08',
        playCount: 156000,
        isNew: true,
        features: ['多种武器', 'Boss战', '升级系统'],
        tags: ['shooting', 'space', 'action']
    },
    {
        id: 'peet-sneak',
        title: 'Peet Sneak',
        category: 'action',
        image: 'img/Peet Sneak.jpg',
        url: 'https://play.famobi.com/peet-sneak',
        description: '通过潜行躲避敌人，在这款隐身动作游戏中执行危险任务。需要策略和时机掌握。',
        rating: 4.4,
        releaseDate: '2023-11-20',
        playCount: 78000,
        isNew: true,
        features: ['隐身元素', '关卡设计', '技能提升'],
        tags: ['action', 'stealth', 'adventure']
    },
    {
        id: 'bubble-tower',
        title: 'Bubble Tower',
        category: 'puzzle',
        image: 'img/Bubble Tower.jpg',
        url: 'https://play.famobi.com/bubble-tower',
        description: '在这款经典泡泡射击游戏中，瞄准并发射彩色泡泡来匹配和消除塔中的泡泡。',
        rating: 4.3,
        releaseDate: '2023-10-15',
        playCount: 120000,
        isNew: true,
        features: ['经典玩法', '多种关卡', '特殊道具'],
        tags: ['puzzle', 'bubble', 'shooter']
    },
    {
        id: 'mahjong-world',
        title: 'Mahjong World',
        category: 'puzzle',
        image: 'img/Mahjong World.jpg',
        url: 'https://play.famobi.com/mahjong-world',
        description: '在这款传统麻将拼图游戏中，匹配相同的图案来清除棋盘。探索世界各地的麻将风格。',
        rating: 4.5,
        releaseDate: '2023-09-20',
        playCount: 180000,
        isNew: false,
        features: ['多种布局', '全球主题', '计时挑战'],
        tags: ['puzzle', 'mahjong', 'tile']
    },
    {
        id: 'bus-parking',
        title: 'Bus Parking',
        category: 'racing',
        image: 'img/Bus Parking.jpg',
        url: 'https://play.famobi.com/bus-parking',
        description: '精准驾驶大型巴士穿过城市街道并停入指定位置。考验你的驾驶技巧和空间感知能力。',
        rating: 4.2,
        releaseDate: '2023-08-30',
        playCount: 95000,
        isNew: false,
        features: ['真实物理', '多种巴士', '逐渐增加的难度'],
        tags: ['racing', 'parking', 'simulation']
    },
    {
        id: 'crazy-caves',
        title: 'Crazy Caves',
        category: 'adventure',
        image: 'img/Crazy Caves.jpg',
        url: 'https://play.famobi.com/crazy-caves',
        description: '探索神秘洞穴收集宝藏，躲避陷阱和危险生物。这款洞穴冒险游戏需要快速反应和谨慎探索。',
        rating: 4.4,
        releaseDate: '2023-09-10',
        playCount: 130000,
        isNew: false,
        features: ['随机生成关卡', '宝藏收集', '升级系统'],
        tags: ['adventure', 'caves', 'exploration']
    },
    {
        id: 'hoop-royale',
        title: 'Hoop Royale',
        category: 'sports',
        image: 'img/Hoop Royale.jpg',
        url: 'https://play.famobi.com/hoop-royale',
        description: '在这款篮球游戏中挑战对手，投篮得分并成为最终的篮球冠军。测试你的精准度和策略。',
        rating: 4.7,
        releaseDate: '2023-11-05',
        playCount: 220000,
        isNew: true,
        features: ['多种游戏模式', '技能解锁', '在线排行榜'],
        tags: ['sports', 'basketball', 'competition']
    },
    {
        id: 'tnt-bomb',
        title: 'TNT Bomb',
        category: 'action',
        image: 'img/TNT Bomb.jpg',
        url: 'https://play.famobi.com/tnt-bomb',
        description: '策略性地放置炸弹来摧毁建筑物和障碍物。在这款爆破游戏中，时机和位置非常关键。',
        rating: 4.5,
        releaseDate: '2023-10-25',
        playCount: 190000,
        isNew: true,
        features: ['物理引擎', '多种爆炸类型', '关卡挑战'],
        tags: ['action', 'strategy', 'destruction']
    },
    {
        id: 'smarty-bubbles',
        title: 'Smarty Bubbles',
        category: 'puzzle',
        image: 'img/Smarty Bubbles.jpg',
        url: 'https://play.famobi.com/smarty-bubbles',
        description: '发射彩色泡泡来匹配相同颜色的组合。这款智力泡泡游戏需要策略思考和快速反应。',
        rating: 4.4,
        releaseDate: '2023-09-15',
        playCount: 150000,
        isNew: false,
        features: ['益智挑战', '彩色图形', '特殊能力泡泡'],
        tags: ['puzzle', 'bubble', 'match']
    },
    {
        id: 'stack-smash',
        title: 'Stack Smash',
        category: 'casual',
        image: 'img/Stack Smash.jpg',
        url: 'https://play.famobi.com/stack-smash',
        description: '拍击并摧毁层叠的方块来获得高分。这款休闲游戏简单易玩但充满挑战，测试你的反应速度。',
        rating: 4.3,
        releaseDate: '2023-10-18',
        playCount: 110000,
        isNew: true,
        features: ['简单操作', '逐渐加速', '分数挑战'],
        tags: ['casual', 'arcade', 'reflex']
    },
    {
        id: 'mahjong',
        title: 'Mahjong',
        category: 'puzzle',
        image: 'img/Mahjong.jpg',
        url: 'https://play.famobi.com/mahjong',
        description: '匹配相同的麻将牌消除棋盘上所有图案。这款经典麻将连连看游戏考验你的观察力和策略。',
        rating: 4.6,
        releaseDate: '2023-08-20',
        playCount: 200000,
        isNew: false,
        features: ['经典玩法', '多种布局', '提示系统'],
        tags: ['puzzle', 'matching', 'tile']
    },
    {
        id: 'monkey-bounce',
        title: 'Monkey Bounce',
        category: 'action',
        image: 'img/Monkey Bounce.jpg',
        url: 'https://play.famobi.com/monkey-bounce',
        description: '控制猴子在丛林中弹跳，收集水果和宝石。这款动作游戏需要精准的时机和良好的反应能力。',
        rating: 4.3,
        releaseDate: '2023-09-05',
        playCount: 125000,
        isNew: false,
        features: ['丛林场景', '角色升级', '各种障碍物'],
        tags: ['action', 'platform', 'bouncing']
    },
    {
        id: 'curve-ball',
        title: 'Curve Ball',
        category: 'sports',
        image: 'img/Curve Ball.jpg',
        url: 'https://play.famobi.com/curve-ball',
        description: '在这款3D乒乓球游戏中，控制球拍击打来球并制造曲线球。测试你的反应能力和球技。',
        rating: 4.4,
        releaseDate: '2023-10-10',
        playCount: 140000,
        isNew: false,
        features: ['3D图形', '真实物理', '多种难度'],
        tags: ['sports', 'ball', 'ping pong']
    },
    {
        id: 'slice-rush',
        title: 'Slice Rush',
        category: 'action',
        image: 'img/Slice Rush.jpg',
        url: 'https://play.famobi.com/slice-rush',
        description: '快速切割屏幕上出现的物体，避免炸弹并尽可能获得高分。这款动作游戏需要敏捷的手指。',
        rating: 4.5,
        releaseDate: '2023-11-10',
        playCount: 165000,
        isNew: true,
        features: ['流畅切割动作', '组合奖励', '多种物体'],
        tags: ['action', 'reflex', 'slicing']
    },
    {
        id: 'hippo-pizza-chef',
        title: 'Hippo Pizza Chef',
        category: 'casual',
        image: 'img/Hippo Pizza Chef.jpg',
        url: 'https://play.famobi.com/hippo-pizza-chef',
        description: '扮演河马厨师制作各种美味披萨。这款休闲游戏中你需要准备食材、烹饪并为顾客服务。',
        rating: 4.2,
        releaseDate: '2023-09-25',
        playCount: 105000,
        isNew: false,
        features: ['多种配料', '时间管理', '厨房升级'],
        tags: ['casual', 'cooking', 'time management']
    },
    {
        id: 'domino-frenzy',
        title: 'Domino Frenzy',
        category: 'puzzle',
        image: 'img/Domino Frenzy.jpg',
        url: 'https://play.famobi.com/domino-frenzy',
        description: '摆放多米诺骨牌创造连锁反应。这款益智游戏需要战略思维和耐心，挑战你的规划能力。',
        rating: 4.3,
        releaseDate: '2023-10-30',
        playCount: 115000,
        isNew: true,
        features: ['物理引擎', '关卡设计', '特殊骨牌'],
        tags: ['puzzle', 'domino', 'chain reaction']
    },
    {
        id: 'cannon-balls',
        title: 'Cannon Balls',
        category: 'action',
        image: 'img/Cannon Balls.jpg',
        url: 'https://play.famobi.com/cannon-balls',
        description: '发射炮弹击破目标，获得高分。这款射击游戏需要计算角度和力量，满足你的破坏欲。',
        rating: 4.4,
        releaseDate: '2023-11-15',
        playCount: 135000,
        isNew: true,
        features: ['物理模拟', '炮弹升级', '关卡挑战'],
        tags: ['action', 'cannon', 'shooting']
    },
    {
        id: 'pets-rush',
        title: 'Pets Rush',
        category: 'casual',
        image: 'img/Pets Rush.jpg',
        url: 'https://play.famobi.com/pets-rush',
        description: '帮助可爱的宠物们奔跑并收集沿途的物品。这款休闲游戏有着丰富的角色和道具。',
        rating: 4.3,
        releaseDate: '2023-09-28',
        playCount: 120000,
        isNew: false,
        features: ['多种宠物', '道具收集', '障碍躲避'],
        tags: ['casual', 'running', 'pets']
    },
    {
        id: 'zoo-feeder',
        title: 'Zoo Feeder',
        category: 'casual',
        image: 'img/Zoo Feeder.jpg',
        url: 'https://play.famobi.com/zoo-feeder',
        description: '喂养动物园中的各种动物，确保它们得到合适的食物。这款模拟游戏考验你的反应和记忆能力。',
        rating: 4.2,
        releaseDate: '2023-10-05',
        playCount: 90000,
        isNew: false,
        features: ['多种动物', '时间管理', '升级系统'],
        tags: ['casual', 'animals', 'management']
    },
    {
        id: 'crossover',
        title: 'Crossover',
        category: 'casual',
        image: 'img/Crossover.jpg',
        url: 'https://play.famobi.com/crossover',
        description: '控制小球穿过繁忙的道路和障碍物。这款休闲游戏需要精准的时机和良好的反应能力。',
        rating: 4.1,
        releaseDate: '2023-09-18',
        playCount: 85000,
        isNew: false,
        features: ['简单操作', '逐渐增加的难度', '解锁内容'],
        tags: ['casual', 'arcade', 'timing']
    },
    {
        id: 'element-balls',
        title: 'Element Balls',
        category: 'puzzle',
        image: 'img/Element Balls.jpg',
        url: 'https://play.famobi.com/element-balls',
        description: '将不同元素的球结合在一起创造新元素。这款益智游戏鼓励探索和发现不同的元素组合。',
        rating: 4.5,
        releaseDate: '2023-11-02',
        playCount: 110000,
        isNew: true,
        features: ['元素合成', '科学启发', '进度保存'],
        tags: ['puzzle', 'elements', 'combination']
    },
    {
        id: 'tower-crash',
        title: 'Tower Crash',
        category: 'action',
        image: 'img/Tower Crash.jpg',
        url: 'https://play.famobi.com/tower-crash',
        description: '摧毁高塔并使其倒塌。这款物理破坏游戏需要策略性地选择攻击点来最大化破坏效果。',
        rating: 4.4,
        releaseDate: '2023-10-22',
        playCount: 145000,
        isNew: true,
        features: ['物理引擎', '多种武器', '关卡设计'],
        tags: ['action', 'destruction', 'physics']
    },
    {
        id: 'sushi-roll',
        title: 'Sushi Roll',
        category: 'casual',
        image: 'img/Sushi Roll.jpg',
        url: 'https://play.famobi.com/sushi-roll',
        description: '经营你自己的寿司店，准备和提供各种美味寿司。这款模拟游戏考验你的时间管理和厨艺。',
        rating: 4.3,
        releaseDate: '2023-09-15',
        playCount: 130000,
        isNew: false,
        features: ['多种寿司制作', '顾客管理', '餐厅升级'],
        tags: ['casual', 'cooking', 'management']
    },
    {
        id: 'onet-world',
        title: 'Onet World',
        category: 'puzzle',
        image: 'img/Onet World.jpg',
        url: 'https://play.famobi.com/onet-world',
        description: '连接相同的图案来清除游戏板。这款经典连连看游戏设有多种主题和难度级别。',
        rating: 4.6,
        releaseDate: '2023-08-25',
        playCount: 195000,
        isNew: false,
        features: ['多种主题', '提示系统', '计时挑战'],
        tags: ['puzzle', 'matching', 'connect']
    },
    {
        id: 'blocks-puzzle-zoo',
        title: 'Blocks Puzzle Zoo',
        category: 'puzzle',
        image: 'img/Blocks Puzzle Zoo.jpg',
        url: 'https://play.famobi.com/blocks-puzzle-zoo',
        description: '将动物形状的方块拼合到网格中。这款益智游戏鼓励空间思维和战略规划。',
        rating: 4.3,
        releaseDate: '2023-11-08',
        playCount: 100000,
        isNew: true,
        features: ['动物主题', '多种难度', '无时间限制'],
        tags: ['puzzle', 'blocks', 'animals']
    },
    {
        id: 'emergency-surgery',
        title: 'Emergency Surgery',
        category: 'simulation',
        image: 'img/Emergency Surgery.jpg',
        url: 'https://play.famobi.com/emergency-surgery',
        description: '扮演急诊外科医生，执行各种紧急手术。这款模拟游戏测试你的稳定性和医疗知识。',
        rating: 4.4,
        releaseDate: '2023-10-15',
        playCount: 125000,
        isNew: true,
        features: ['医疗工具', '紧急情况', '多种手术类型'],
        tags: ['simulation', 'medical', 'surgery']
    },
    {
        id: 'element-blocks',
        title: 'Element Blocks',
        category: 'puzzle',
        image: 'img/Element Blocks.jpg',
        url: 'https://play.famobi.com/element-blocks',
        description: '移动和组合不同元素的方块，创造反应和解决谜题。这款益智游戏基于化学元素原理。',
        rating: 4.5,
        releaseDate: '2023-09-30',
        playCount: 115000,
        isNew: false,
        features: ['元素互动', '创意玩法', '逻辑思维'],
        tags: ['puzzle', 'elements', 'blocks']
    },
    {
        id: 'zoo-boom',
        title: 'Zoo Boom',
        category: 'puzzle',
        image: 'img/Zoo Boom.jpg',
        url: 'https://play.famobi.com/zoo-boom',
        description: '匹配三个或更多相同的动物图案来获得分数。这款动物园主题的消除游戏充满了可爱的角色。',
        rating: 4.2,
        releaseDate: '2023-10-25',
        playCount: 105000,
        isNew: true,
        features: ['动物主题', '组合奖励', '关卡挑战'],
        tags: ['puzzle', 'match3', 'animals']
    },
    {
        id: 'pirate-cards',
        title: 'Pirate Cards',
        category: 'puzzle',
        image: 'img/Pirate Cards.jpg',
        url: 'https://play.famobi.com/pirate-cards',
        description: '体验这款海盗主题的扑克牌游戏，根据牌面收集财宝和作战。策略和运气都很重要。',
        rating: 4.3,
        releaseDate: '2023-11-12',
        playCount: 95000,
        isNew: true,
        features: ['海盗主题', '牌局策略', '宝藏收集'],
        tags: ['puzzle', 'cards', 'pirate']
    },
    {
        id: 'moto-x',
        title: 'Moto X',
        category: 'racing',
        image: 'img/Moto X.jpg',
        url: 'https://play.famobi.com/moto-x',
        description: '骑着摩托车穿越崎岖地形，执行惊险特技。这款极限摩托车游戏考验你的平衡和控制能力。',
        rating: 4.5,
        releaseDate: '2023-09-20',
        playCount: 160000,
        isNew: false,
        features: ['极限特技', '多种赛道', '摩托车升级'],
        tags: ['racing', 'motocross', 'stunts']
    },
    {
        id: 'wiggle',
        title: 'Wiggle',
        category: 'casual',
        image: 'img/Wiggle.jpg',
        url: 'https://play.famobi.com/wiggle',
        description: '控制一条蠕动的线条，避开障碍物并尽可能地成长。这款休闲游戏简单而具有挑战性。',
        rating: 4.1,
        releaseDate: '2023-10-10',
        playCount: 85000,
        isNew: false,
        features: ['简单控制', '逐渐增加的难度', '多种主题'],
        tags: ['casual', 'arcade', 'snake']
    },
    {
        id: 'adventure-drivers',
        title: 'Adventure Drivers',
        category: 'racing',
        image: 'img/Adventure Drivers.jpg',
        url: 'https://play.famobi.com/adventure-drivers',
        description: '驾驶各种车辆穿越充满挑战的地形，完成刺激的冒险任务。这款驾驶游戏结合了竞速和冒险元素。',
        rating: 4.5,
        releaseDate: '2023-11-05',
        playCount: 142000,
        isNew: true,
        features: ['多种车辆', '不同地形', '任务系统'],
        tags: ['racing', 'adventure', 'driving']
    },
    {
        id: 'solitaire-legend',
        title: 'Solitaire Legend',
        category: 'puzzle',
        image: 'img/Solitaire Legend.jpg',
        url: 'https://play.famobi.com/solitaire-legend',
        description: '体验这款经典纸牌游戏的数字版本，享受简洁界面和流畅操作。不同难度级别满足所有玩家需求。',
        rating: 4.7,
        releaseDate: '2023-10-15',
        playCount: 185000,
        isNew: true,
        features: ['经典玩法', '不同主题', '成就系统'],
        tags: ['puzzle', 'cards', 'solitaire']
    },
    {
        id: 'kawaii-chibi-creator',
        title: 'Kawaii Chibi Creator',
        category: 'casual',
        image: 'img/Kawaii Chibi Creator.jpg',
        url: 'https://play.famobi.com/kawaii-chibi-creator',
        description: '创建你自己的可爱卡通人物，选择各种服装、发型和配饰。这款时尚游戏让你发挥创意设计可爱角色。',
        rating: 4.4,
        releaseDate: '2023-09-18',
        playCount: 128000,
        isNew: true,
        features: ['角色定制', '多种风格', '分享功能'],
        tags: ['casual', 'dress-up', 'creativity']
    },
    {
        id: 'find-in-mind',
        title: 'Find in Mind',
        category: 'puzzle',
        image: 'img/Find in Mind.jpg',
        url: 'https://play.famobi.com/find-in-mind',
        description: '测试你的观察力和记忆能力，找出隐藏的物品和图案。这款益智游戏富有挑战性，适合所有年龄段玩家。',
        rating: 4.3,
        releaseDate: '2023-08-22',
        playCount: 95000,
        isNew: false,
        features: ['大脑训练', '多样关卡', '计时挑战'],
        tags: ['puzzle', 'hidden object', 'memory']
    },
    {
        id: 'merge-jewels',
        title: 'Merge Jewels',
        category: 'puzzle',
        image: 'img/Merge Jewels.jpg',
        url: 'https://play.famobi.com/merge-jewels',
        description: '通过合并相同的宝石来创造更高级的宝石。这款策略合并游戏需要规划和思考，让你沉浸在珠宝世界中。',
        rating: 4.5,
        releaseDate: '2023-07-10',
        playCount: 156000,
        isNew: false,
        features: ['合并机制', '视觉效果', '升级系统'],
        tags: ['puzzle', 'merge', 'jewels']
    },
    {
        id: 'high-hills',
        title: 'High Hills',
        category: 'sports',
        image: 'img/High Hills.jpg',
        url: 'https://play.famobi.com/high-hills',
        description: '控制滑雪者滑下陡峭的山坡，执行惊险特技，避开障碍物。这款滑雪游戏具有流畅的操控和精美的雪景。',
        rating: 4.6,
        releaseDate: '2023-12-01',
        playCount: 132000,
        isNew: true,
        features: ['滑雪特技', '山地场景', '装备升级'],
        tags: ['sports', 'skiing', 'winter']
    },
    {
        id: 'knife-rain',
        title: 'Knife Rain',
        category: 'action',
        image: 'img/Knife Rain.jpg',
        url: 'https://play.famobi.com/knife-rain',
        description: '躲避从天而降的飞刀，测试你的反应速度和敏捷度。这款紧张刺激的动作游戏需要精确的时机和极快的反应。',
        rating: 4.2,
        releaseDate: '2023-11-28',
        playCount: 110000,
        isNew: true,
        features: ['紧张刺激', '增加难度', '反应挑战'],
        tags: ['action', 'reflex', 'dodging']
    },
    {
        id: 'maze',
        title: 'Maze',
        category: 'puzzle',
        image: 'img/Maze.jpg',
        url: 'https://play.famobi.com/maze',
        description: '在复杂迷宫中寻找出路，解锁不同的关卡和挑战。这款经典迷宫游戏考验你的方向感和解谜能力。',
        rating: 4.4,
        releaseDate: '2023-06-15',
        playCount: 145000,
        isNew: false,
        features: ['多样迷宫', '递增难度', '解谜元素'],
        tags: ['puzzle', 'maze', 'navigation']
    },
    {
        id: 'bunny-quest',
        title: 'Bunny Quest',
        category: 'adventure',
        image: 'img/Bunny Quest.jpg',
        url: 'https://play.famobi.com/bunny-quest',
        description: '帮助可爱的兔子在冒险中收集胡萝卜，躲避敌人，解决谜题。这款冒险游戏充满了可爱元素和挑战。',
        rating: 4.5,
        releaseDate: '2023-04-10',
        playCount: 120000,
        isNew: false,
        features: ['探索世界', '解谜元素', '角色成长'],
        tags: ['adventure', 'cute', 'platformer']
    },
    {
        id: 'drag-racing-club',
        title: 'Drag Racing Club',
        category: 'racing',
        image: 'img/Drag Racing Club.jpg',
        url: 'https://play.famobi.com/drag-racing-club',
        description: '参加直线加速赛，与对手一较高下。调整你的车辆，掌握完美的换挡时机，成为街头赛车冠军。',
        rating: 4.7,
        releaseDate: '2023-09-05',
        playCount: 175000,
        isNew: true,
        features: ['车辆升级', '竞争模式', '真实物理'],
        tags: ['racing', 'cars', 'drag']
    },
    {
        id: 'baby-lily-care',
        title: 'Baby Lily Care',
        category: 'simulation',
        image: 'img/Baby Lily Care.jpg',
        url: 'https://play.famobi.com/baby-lily-care',
        description: '照顾可爱的小莉莉，满足她的各种需求，确保她快乐健康。这款育儿模拟游戏让你体验照顾宝宝的乐趣。',
        rating: 4.3,
        releaseDate: '2023-05-20',
        playCount: 115000,
        isNew: false,
        features: ['育儿活动', '角色互动', '多种场景'],
        tags: ['simulation', 'kids', 'care']
    },
    {
        id: 'baby-lily-birthday',
        title: 'Baby Lily Birthday',
        category: 'simulation',
        image: 'img/Baby Lily Birthday.jpg',
        url: 'https://play.famobi.com/baby-lily-birthday',
        description: '为小莉莉准备一个完美的生日派对，装饰房间，准备蛋糕，邀请朋友。这款派对游戏充满了欢乐和创意。',
        rating: 4.2,
        releaseDate: '2023-07-15',
        playCount: 98000,
        isNew: false,
        features: ['派对准备', '蛋糕制作', '装饰活动'],
        tags: ['simulation', 'birthday', 'party']
    },
    {
        id: 'baby-lily-sick-day',
        title: 'Baby Lily Sick Day',
        category: 'simulation',
        image: 'img/Baby Lily Sick Day.jpg',
        url: 'https://play.famobi.com/baby-lily-sick-day',
        description: '小莉莉生病了，照顾她恢复健康。这款照顾游戏让你体验照料生病小孩的责任和关爱。',
        rating: 4.1,
        releaseDate: '2023-08-30',
        playCount: 90000,
        isNew: false,
        features: ['医疗照顾', '恢复活动', '互动元素'],
        tags: ['simulation', 'medical', 'care']
    },
    {
        id: 'dunk-brush',
        title: 'Dunk Brush',
        category: 'casual',
        image: 'img/Dunk Brush.jpg',
        url: 'https://play.famobi.com/dunk-brush',
        description: '用画笔创造路径，引导篮球入框得分。这款创意游戏结合了绘画和篮球元素，带来独特的游戏体验。',
        rating: 4.4,
        releaseDate: '2023-10-25',
        playCount: 130000,
        isNew: true,
        features: ['创意玩法', '物理引擎', '挑战关卡'],
        tags: ['casual', 'drawing', 'basketball']
    },
    {
        id: 'goalkeeper-champ',
        title: 'Goalkeeper Champ',
        category: 'sports',
        image: 'img/Goalkeeper Champ.jpg',
        url: 'https://play.famobi.com/goalkeeper-champ',
        description: '扮演守门员，阻挡对手的射门，展示你的反应能力和判断力。这款足球游戏专注于守门技巧和时机。',
        rating: 4.6,
        releaseDate: '2023-11-10',
        playCount: 165000,
        isNew: true,
        features: ['快速反应', '多种挑战', '锦标赛模式'],
        tags: ['sports', 'soccer', 'goalkeeper']
    },
    {
        id: 'my-fairytale-deer',
        title: 'My Fairytale Deer',
        category: 'casual',
        image: 'img/My Fairytale Deer.jpg',
        url: 'https://play.famobi.com/my-fairytale-deer',
        description: '照顾并装扮一只童话鹿，让它变得美丽动人。这款温馨的游戏让你沉浸在童话世界中，发挥创意。',
        rating: 4.2,
        releaseDate: '2023-06-08',
        playCount: 85000,
        isNew: false,
        features: ['角色装扮', '互动元素', '多种造型'],
        tags: ['casual', 'animals', 'dress-up']
    },
    {
        id: 'my-fairytale-water-horse',
        title: 'My Fairytale Water Horse',
        category: 'casual',
        image: 'img/My Fairytale Water Horse.jpg',
        url: 'https://play.famobi.com/my-fairytale-water-horse',
        description: '照顾并装扮一匹神奇的水马，创造属于你的童话伙伴。这款游戏充满魔法元素和创意可能性。',
        rating: 4.3,
        releaseDate: '2023-07-22',
        playCount: 92000,
        isNew: false,
        features: ['幻想元素', '马匹装扮', '场景互动'],
        tags: ['casual', 'fantasy', 'horse']
    },
    {
        id: 'blaze-kick',
        title: 'Blaze Kick',
        category: 'sports',
        image: 'img/Blaze Kick.jpg',
        url: 'https://play.famobi.com/blaze-kick',
        description: '展示你的足球技巧，射入燃烧的球门得分。这款极限足球游戏结合了技巧和时机，充满视觉效果。',
        rating: 4.5,
        releaseDate: '2023-10-18',
        playCount: 140000,
        isNew: true,
        features: ['视觉特效', '技能挑战', '难度递增'],
        tags: ['sports', 'soccer', 'extreme']
    },
    {
        id: 'happy-panda',
        title: 'Happy Panda',
        category: 'casual',
        image: 'img/Happy Panda.jpg',
        url: 'https://play.famobi.com/happy-panda',
        description: '照顾可爱的熊猫，满足它的需求，让它快乐成长。这款休闲游戏充满了萌萌的熊猫互动。',
        rating: 4.3,
        releaseDate: '2023-08-12',
        playCount: 115000,
        isNew: false,
        features: ['熊猫互动', '喂食活动', '环境探索'],
        tags: ['casual', 'animal', 'cute']
    },
    {
        id: 'happy-koala',
        title: 'Happy Koala',
        category: 'casual',
        image: 'img/Happy Koala.jpg',
        url: 'https://play.famobi.com/happy-koala',
        description: '帮助考拉收集桉树叶，攀爬树木，躲避危险。这款休闲游戏让你体验考拉的日常生活。',
        rating: 4.2,
        releaseDate: '2023-09-05',
        playCount: 105000,
        isNew: true,
        features: ['动物生活', '收集元素', '树木攀爬'],
        tags: ['casual', 'animal', 'cute']
    },
    {
        id: 'perfect-piano',
        title: 'Perfect Piano',
        category: 'casual',
        image: 'img/Perfect Piano.jpg',
        url: 'https://play.famobi.com/perfect-piano',
        description: '在虚拟钢琴上弹奏你喜爱的曲子，学习音乐，提高技巧。这款音乐游戏适合初学者和音乐爱好者。',
        rating: 4.6,
        releaseDate: '2023-05-28',
        playCount: 158000,
        isNew: false,
        features: ['真实钢琴音色', '乐谱学习', '录制功能'],
        tags: ['casual', 'music', 'educational']
    },
    {
        id: 'sailor-girls-avatar-maker',
        title: 'Sailor Girls Avatar Maker',
        category: 'casual',
        image: 'img/Sailor Girls Avatar Maker.jpg',
        url: 'https://play.famobi.com/sailor-girls-avatar-maker',
        description: '创建你自己的水手少女角色，选择不同的发型、服装和配饰。这款角色创建游戏灵感来自经典动漫。',
        rating: 4.4,
        releaseDate: '2023-11-15',
        playCount: 125000,
        isNew: true,
        features: ['多样定制', '动漫风格', '分享功能'],
        tags: ['casual', 'avatar', 'anime']
    },
    {
        id: 'cheap-golf',
        title: 'Cheap Golf',
        category: 'sports',
        image: 'img/Cheap Golf.jpg',
        url: 'https://play.famobi.com/cheap-golf',
        description: '在这款简约迷你高尔夫游戏中，计算角度和力量，用最少的杆数完成每个球洞。',
        rating: 4.3,
        releaseDate: '2023-07-30',
        playCount: 110000,
        isNew: false,
        features: ['简约界面', '物理引擎', '多样球道'],
        tags: ['sports', 'golf', 'mini-golf']
    },
    {
        id: 'jigsaw-puzzle-deluxe',
        title: 'Jigsaw Puzzle Deluxe',
        category: 'puzzle',
        image: 'img/Jigsaw Puzzle Deluxe.jpg',
        url: 'https://play.famobi.com/jigsaw-puzzle-deluxe',
        description: '享受高品质的拼图游戏体验，挑战不同难度的美丽图画。这款拼图游戏适合所有年龄段玩家。',
        rating: 4.7,
        releaseDate: '2023-08-08',
        playCount: 175000,
        isNew: false,
        features: ['精美图画', '多种难度', '放松体验'],
        tags: ['puzzle', 'jigsaw', 'relaxing']
    },
    {
        id: 'bubble-woods',
        title: 'Bubble Woods',
        category: 'puzzle',
        image: 'img/Bubble Woods.jpg',
        url: 'https://play.famobi.com/bubble-woods',
        description: '在森林背景中射击彩色泡泡，匹配并消除相同颜色的组合。这款泡泡射击游戏有着精美的自然主题。',
        rating: 4.5,
        releaseDate: '2023-09-25',
        playCount: 140000,
        isNew: true,
        features: ['森林主题', '泡泡匹配', '特殊道具'],
        tags: ['puzzle', 'bubble', 'nature']
    },
    {
        id: 'cute-unicorn-care',
        title: 'Cute Unicorn Care',
        category: 'casual',
        image: 'img/Cute Unicorn Care.jpg',
        url: 'https://play.famobi.com/cute-unicorn-care',
        description: '照顾一只神奇的独角兽，喂食、洗澡和装扮它。这款游戏充满了幻想元素和可爱互动。',
        rating: 4.4,
        releaseDate: '2023-06-20',
        playCount: 130000,
        isNew: false,
        features: ['独角兽互动', '美容活动', '魔法元素'],
        tags: ['casual', 'unicorn', 'care']
    },
    {
        id: 'kumba-kool',
        title: 'Kumba Kool',
        category: 'action',
        image: 'img/Kumba Kool.jpg',
        url: 'https://play.famobi.com/kumba-kool',
        description: '控制酷炫的角色在多彩世界中奔跑和跳跃，收集物品并避开障碍物。这款动作游戏充满节奏感和活力。',
        rating: 4.3,
        releaseDate: '2023-10-30',
        playCount: 98000,
        isNew: true,
        features: ['多彩世界', '角色技能', '关卡挑战'],
        tags: ['action', 'platform', 'collection']
    },
    {
        id: 'soccer-champ',
        title: 'Soccer Champ',
        category: 'sports',
        image: 'img/Soccer Champ.jpg',
        url: 'https://play.famobi.com/soccer-champ',
        description: '体验真实的足球比赛，控制你的球员进攻、防守和射门。这款足球游戏提供完整的比赛体验。',
        rating: 4.6,
        releaseDate: '2023-11-20',
        playCount: 180000,
        isNew: true,
        features: ['完整比赛', '球员控制', '战术选择'],
        tags: ['sports', 'soccer', 'team']
    },
    {
        id: 'soccertastic-world-cup',
        title: 'Soccertastic World Cup',
        category: 'sports',
        image: 'img/Soccertastic World Cup.jpg',
        url: 'https://play.famobi.com/soccertastic-world-cup',
        description: '参加世界杯足球赛，代表你的国家争夺最高荣誉。这款足球游戏让你体验国际赛事的激情。',
        rating: 4.7,
        releaseDate: '2023-12-05',
        playCount: 195000,
        isNew: true,
        features: ['国际队伍', '锦标赛模式', '球员技能'],
        tags: ['sports', 'soccer', 'world cup']
    },
    {
        id: 'my-fairytale-tiger',
        title: 'My Fairytale Tiger',
        category: 'casual',
        image: 'img/My Fairytale Tiger.jpg',
        url: 'https://play.famobi.com/my-fairytale-tiger',
        description: '照顾并装扮一只童话老虎，创造你专属的魔法伙伴。这款游戏融合了照顾和创意元素。',
        rating: 4.2,
        releaseDate: '2023-08-15',
        playCount: 95000,
        isNew: false,
        features: ['老虎互动', '装饰元素', '故事情节'],
        tags: ['casual', 'animal', 'fantasy']
    },
    {
        id: 'happy-lemur',
        title: 'Happy Lemur',
        category: 'casual',
        image: 'img/Happy Lemur.jpg',
        url: 'https://play.famobi.com/happy-lemur',
        description: '帮助狐猴在森林中寻找食物，躲避危险，完成各种挑战。这款休闲游戏充满了可爱角色和热带风情。',
        rating: 4.3,
        releaseDate: '2023-09-12',
        playCount: 88000,
        isNew: true,
        features: ['森林冒险', '食物收集', '动物互动'],
        tags: ['casual', 'animal', 'collection']
    },
    {
        id: 'tap-my-water',
        title: 'Tap My Water',
        category: 'puzzle',
        image: 'img/Tap My Water.jpg',
        url: 'https://play.famobi.com/tap-my-water',
        description: '通过连接水管和阀门，引导水流到达目标。这款物理益智游戏需要逻辑思考和规划能力。',
        rating: 4.5,
        releaseDate: '2023-07-05',
        playCount: 135000,
        isNew: false,
        features: ['水流物理', '多样关卡', '思维挑战'],
        tags: ['puzzle', 'water', 'pipes']
    },
    {
        id: 'pie-realife-cooking',
        title: 'Pie Realife Cooking',
        category: 'simulation',
        image: 'img/Pie Realife Cooking.jpg',
        url: 'https://play.famobi.com/pie-realife-cooking',
        description: '学习制作各种美味的派，从准备食材到完成装饰。这款烹饪模拟游戏让你体验真实的烘焙过程。',
        rating: 4.4,
        releaseDate: '2023-10-10',
        playCount: 120000,
        isNew: true,
        features: ['真实烹饪', '多种食谱', '创意装饰'],
        tags: ['simulation', 'cooking', 'food']
    },
    {
        id: 'pizza-realife-cooking',
        title: 'Pizza Realife Cooking',
        category: 'simulation',
        image: 'img/Pizza Realife Cooking.jpg',
        url: 'https://play.famobi.com/pizza-realife-cooking',
        description: '成为披萨大厨，制作各种风味的披萨，从和面到添加配料。这款烹饪游戏提供真实的披萨制作体验。',
        rating: 4.5,
        releaseDate: '2023-11-05',
        playCount: 145000,
        isNew: true,
        features: ['多种配料', '烹饪步骤', '顾客订单'],
        tags: ['simulation', 'cooking', 'pizza']
    },
    {
        id: 'world-cup-penalty',
        title: 'World Cup Penalty',
        category: 'sports',
        image: 'img/World Cup Penalty.jpg',
        url: 'https://play.famobi.com/world-cup-penalty',
        description: '体验世界杯点球大战的紧张刺激，扮演射手或守门员。这款足球游戏专注于点球环节的技巧和心理。',
        rating: 4.6,
        releaseDate: '2023-12-12',
        playCount: 170000,
        isNew: true,
        features: ['国际球队', '守门模式', '射门模式'],
        tags: ['sports', 'soccer', 'penalty']
    },
    {
        id: 'race-right',
        title: 'Race Right',
        category: 'racing',
        image: 'img/Race Right.jpg',
        url: 'https://play.famobi.com/race-right',
        description: '在各种具有挑战性的赛道上驾驶赛车，争取最佳时间和完美表现。这款赛车游戏需要精确控制和策略。',
        rating: 4.4,
        releaseDate: '2023-10-22',
        playCount: 128000,
        isNew: true,
        features: ['多样赛道', '车辆升级', '竞速挑战'],
        tags: ['racing', 'cars', 'speed']
    },
    {
        id: 'mahjong-flowers',
        title: 'Mahjong Flowers',
        category: 'puzzle',
        image: 'img/Mahjong Flowers.jpg',
        url: 'https://play.famobi.com/mahjong-flowers',
        description: '在这款花卉主题的麻将游戏中，匹配并消除相同的牌，欣赏精美的花卉图案。',
        rating: 4.5,
        releaseDate: '2023-09-08',
        playCount: 155000,
        isNew: true,
        features: ['花卉主题', '多样布局', '休闲玩法'],
        tags: ['puzzle', 'mahjong', 'flowers']
    },
    {
        id: 'tina-detective',
        title: 'Tina Detective',
        category: 'adventure',
        image: 'img/Tina Detective.jpg',
        url: 'https://play.famobi.com/tina-detective',
        description: '跟随侦探蒂娜解决神秘案件，寻找线索，推理真相。这款侦探冒险游戏充满悬疑和智力挑战。',
        rating: 4.3,
        releaseDate: '2023-08-20',
        playCount: 105000,
        isNew: false,
        features: ['案件调查', '线索收集', '故事情节'],
        tags: ['adventure', 'detective', 'mystery']
    },
    {
        id: 'nina-detective',
        title: 'Nina Detective',
        category: 'adventure',
        image: 'img/Nina Detective.jpg',
        url: 'https://play.famobi.com/nina-detective',
        description: '帮助侦探妮娜破解复杂案件，搜集证据，找出嫌疑人。这款侦探游戏需要细心观察和逻辑思考。',
        rating: 4.4,
        releaseDate: '2023-11-18',
        playCount: 115000,
        isNew: true,
        features: ['侦探故事', '解谜元素', '角色互动'],
        tags: ['adventure', 'detective', 'logic']
    },
    {
        id: 'dominoes-classic',
        title: 'Dominoes Classic',
        category: 'puzzle',
        image: 'img/Dominoes Classic.jpg',
        url: 'https://play.famobi.com/dominoes-classic',
        description: '体验经典的多米诺骨牌游戏，与对手对战，策略性地放置骨牌。这款桌游适合所有年龄段的玩家。',
        rating: 4.7,
        releaseDate: '2023-07-25',
        playCount: 190000,
        isNew: false,
        features: ['经典规则', '多人对战', '排行榜系统'],
        tags: ['puzzle', 'dominoes', 'classic']
    },
    {
        id: 'cute-puppy-care',
        title: 'Cute Puppy Care',
        category: 'casual',
        image: 'img/Cute Puppy Care.jpg',
        url: 'https://play.famobi.com/cute-puppy-care',
        description: '照顾可爱的小狗，喂食、洗澡、玩耍和装饰。这款宠物模拟游戏让你体验养狗的乐趣。',
        rating: 4.4,
        releaseDate: '2023-08-05',
        playCount: 128000,
        isNew: false,
        features: ['宠物护理', '装饰选项', '互动游戏'],
        tags: ['casual', 'pet', 'care']
    },
    {
        id: 'cute-kitty-care',
        title: 'Cute Kitty Care',
        category: 'casual',
        image: 'img/Cute Kitty Care.jpg',
        url: 'https://play.famobi.com/cute-kitty-care',
        description: '照顾可爱的小猫咪，满足它的各种需求。这款宠物模拟游戏充满了萌猫互动和玩法。',
        rating: 4.3,
        releaseDate: '2023-09-10',
        playCount: 135000,
        isNew: true,
        features: ['猫咪互动', '装饰房间', '多种猫咪种类'],
        tags: ['casual', 'pet', 'cat']
    },
    {
        id: 'tina-pop-star',
        title: 'Tina Pop Star',
        category: 'casual',
        image: 'img/Tina Pop Star.jpg',
        url: 'https://play.famobi.com/tina-pop-star',
        description: '帮助蒂娜成为顶尖流行歌星，打造她的形象，安排演出，录制歌曲。这款模拟游戏让你体验明星生活。',
        rating: 4.5,
        releaseDate: '2023-07-15',
        playCount: 142000,
        isNew: false,
        features: ['明星装扮', '音乐表演', '粉丝互动'],
        tags: ['casual', 'music', 'fashion']
    },
    {
        id: 'nina-pop-star',
        title: 'Nina Pop Star',
        category: 'casual',
        image: 'img/Nina Pop Star.jpg',
        url: 'https://play.famobi.com/nina-pop-star',
        description: '帮助妮娜实现她的流行歌星梦想，从选择服装到表演舞台。这款游戏让你体验成为明星的全过程。',
        rating: 4.4,
        releaseDate: '2023-08-20',
        playCount: 138000,
        isNew: false,
        features: ['舞台表演', '装扮搭配', '歌曲创作'],
        tags: ['casual', 'music', 'fashion']
    },
    {
        id: 'kitchen-mahjong-classic',
        title: 'Kitchen Mahjong Classic',
        category: 'puzzle',
        image: 'img/Kitchen Mahjong Classic.jpg',
        url: 'https://play.famobi.com/kitchen-mahjong-classic',
        description: '在厨房主题的麻将游戏中匹配厨具和食物图案。这款休闲益智游戏结合了经典麻将和美食元素。',
        rating: 4.6,
        releaseDate: '2023-06-18',
        playCount: 165000,
        isNew: false,
        features: ['美食主题', '传统玩法', '精美图案'],
        tags: ['puzzle', 'mahjong', 'kitchen']
    },
    {
        id: 'color-pixel-art-classic',
        title: 'Color Pixel Art Classic',
        category: 'puzzle',
        image: 'img/Color Pixel Art Classic.jpg',
        url: 'https://play.famobi.com/color-pixel-art-classic',
        description: '根据数字填色创建精美的像素艺术。这款填色游戏让你放松心情的同时创造像素艺术作品。',
        rating: 4.5,
        releaseDate: '2023-05-25',
        playCount: 152000,
        isNew: false,
        features: ['数字填色', '多种图案', '作品分享'],
        tags: ['puzzle', 'coloring', 'pixel art']
    },
    {
        id: 'mahjong-connect-classic',
        title: 'Mahjong Connect Classic',
        category: 'puzzle',
        image: 'img/Mahjong Connect Classic.jpg',
        url: 'https://play.famobi.com/mahjong-connect-classic',
        description: '连接相同的麻将牌，但只能通过三个或更少的直线转弯连接。这款经典连连看游戏考验你的观察力。',
        rating: 4.7,
        releaseDate: '2023-04-12',
        playCount: 185000,
        isNew: false,
        features: ['经典玩法', '多层关卡', '计时挑战'],
        tags: ['puzzle', 'mahjong', 'connect']
    },
    {
        id: 'defly',
        title: 'Defly',
        category: 'action',
        image: 'img/Defly.jpg',
        url: 'https://play.famobi.com/defly',
        description: '控制你的飞行器，建造防御墙，攻击对手的基地。这款多人动作游戏结合了策略和反应速度。',
        rating: 4.6,
        releaseDate: '2023-11-05',
        playCount: 174000,
        isNew: true,
        features: ['多人对战', '地盘争夺', '升级系统'],
        tags: ['action', 'multiplayer', 'strategy']
    },
    {
        id: 'my-fairytale-griffin',
        title: 'My Fairytale Griffin',
        category: 'casual',
        image: 'img/My Fairytale Griffin.jpg',
        url: 'https://play.famobi.com/my-fairytale-griffin',
        description: '照顾并装扮一只神奇的狮鹫，培养它的能力，探索魔法世界。这款游戏充满奇幻元素和创意互动。',
        rating: 4.3,
        releaseDate: '2023-08-30',
        playCount: 112000,
        isNew: false,
        features: ['神兽互动', '魔法元素', '装饰系统'],
        tags: ['casual', 'fantasy', 'pet']
    },
    {
        id: 'archery-world-tour',
        title: 'Archery World Tour',
        category: 'sports',
        image: 'img/Archery World Tour.jpg',
        url: 'https://play.famobi.com/archery-world-tour',
        description: '在世界各地的场景中测试你的射箭技巧，挑战各种难度的目标。这款射箭游戏需要精确的瞄准和时机。',
        rating: 4.5,
        releaseDate: '2023-10-20',
        playCount: 148000,
        isNew: true,
        features: ['全球场景', '技能提升', '比赛模式'],
        tags: ['sports', 'archery', 'precision']
    },
    {
        id: 'my-fairytale-unicorn',
        title: 'My Fairytale Unicorn',
        category: 'casual',
        image: 'img/My Fairytale Unicorn.jpg',
        url: 'https://play.famobi.com/my-fairytale-unicorn',
        description: '照顾一只梦幻独角兽，装饰它的鬃毛，探索魔法王国。这款游戏让你沉浸在奇幻的童话世界中。',
        rating: 4.4,
        releaseDate: '2023-07-10',
        playCount: 158000,
        isNew: false,
        features: ['独角兽互动', '彩虹世界', '魔法能力'],
        tags: ['casual', 'fantasy', 'unicorn']
    },
    {
        id: 'happy-elephant',
        title: 'Happy Elephant',
        category: 'casual',
        image: 'img/Happy Elephant.jpg',
        url: 'https://play.famobi.com/happy-elephant',
        description: '照顾可爱的大象，喂食、洗澡、玩耍，确保它快乐健康。这款休闲游戏充满了温馨互动和有趣活动。',
        rating: 4.2,
        releaseDate: '2023-06-08',
        playCount: 105000,
        isNew: false,
        features: ['动物互动', '环境探索', '照顾活动'],
        tags: ['casual', 'animal', 'care']
    },
    {
        id: 'my-fairytale-wolf',
        title: 'My Fairytale Wolf',
        category: 'casual',
        image: 'img/My Fairytale Wolf.jpg',
        url: 'https://play.famobi.com/my-fairytale-wolf',
        description: '养育并装扮一只魔法狼，发展它的能力，探索森林王国。这款奇幻游戏让你体验与野性生物的友谊。',
        rating: 4.3,
        releaseDate: '2023-09-15',
        playCount: 118000,
        isNew: true,
        features: ['狼族互动', '森林探险', '角色成长'],
        tags: ['casual', 'fantasy', 'wolf']
    },
    {
        id: 'my-fairytale-dragon',
        title: 'My Fairytale Dragon',
        category: 'casual',
        image: 'img/My Fairytale Dragon.jpg',
        url: 'https://play.famobi.com/my-fairytale-dragon',
        description: '收养一只幼龙，照顾它成长为强大的巨龙。这款奇幻游戏充满了龙族魔法和史诗冒险。',
        rating: 4.6,
        releaseDate: '2023-11-20',
        playCount: 172000,
        isNew: true,
        features: ['龙之成长', '元素能力', '飞行探索'],
        tags: ['casual', 'fantasy', 'dragon']
    },
    {
        id: 'the-little-giant',
        title: 'The Little Giant',
        category: 'adventure',
        image: 'img/The Little Giant.jpg',
        url: 'https://play.famobi.com/the-little-giant',
        description: '帮助小巨人在充满挑战的世界中冒险，解决谜题，战胜敌人。这款冒险游戏融合了解谜和动作元素。',
        rating: 4.5,
        releaseDate: '2023-10-05',
        playCount: 138000,
        isNew: true,
        features: ['世界探索', '谜题解决', '能力成长'],
        tags: ['adventure', 'puzzle', 'platformer']
    },
    {
        id: 'surfer-archers',
        title: 'Surfer Archers',
        category: 'action',
        image: 'img/Surfer Archers.jpg',
        url: 'https://play.famobi.com/surfer-archers',
        description: '在冲浪的同时射击目标，展示你的多重技能。这款独特的动作游戏结合了冲浪和射箭的乐趣。',
        rating: 4.4,
        releaseDate: '2023-08-12',
        playCount: 125000,
        isNew: false,
        features: ['海浪挑战', '射击精准', '角色升级'],
        tags: ['action', 'sports', 'archery']
    },
    {
        id: 'happy-chipmunk',
        title: 'Happy Chipmunk',
        category: 'casual',
        image: 'img/Happy Chipmunk.jpg',
        url: 'https://play.famobi.com/happy-chipmunk',
        description: '帮助可爱的花栗鼠收集坚果，避开危险，建造舒适的家。这款休闲游戏充满可爱动物和收集乐趣。',
        rating: 4.3,
        releaseDate: '2023-07-28',
        playCount: 106000,
        isNew: false,
        features: ['坚果收集', '避险技巧', '家园建设'],
        tags: ['casual', 'animal', 'collection']
    },
    {
        id: 'happy-bunny',
        title: 'Happy Bunny',
        category: 'casual',
        image: 'img/Happy Bunny.jpg',
        url: 'https://play.famobi.com/happy-bunny',
        description: '照顾可爱的小兔子，喂食胡萝卜，建造兔子洞，避开天敌。这款游戏让你体验照顾小动物的乐趣。',
        rating: 4.2,
        releaseDate: '2023-06-15',
        playCount: 98000,
        isNew: false,
        features: ['兔子护理', '萝卜种植', '洞穴装饰'],
        tags: ['casual', 'animal', 'cute']
    },
    {
        id: 'happy-fox',
        title: 'Happy Fox',
        category: 'casual',
        image: 'img/Happy Fox.jpg',
        url: 'https://play.famobi.com/happy-fox',
        description: '与狡猾的狐狸一起探索森林，狩猎食物，躲避猎人。这款动物模拟游戏让你体验狐狸的日常生活。',
        rating: 4.4,
        releaseDate: '2023-09-02',
        playCount: 115000,
        isNew: true,
        features: ['森林探索', '狩猎技巧', '领地保护'],
        tags: ['casual', 'animal', 'simulation']
    },
    {
        id: 'word-search-classic',
        title: 'Word Search Classic',
        category: 'puzzle',
        image: 'img/Word Search Classic.jpg',
        url: 'https://play.famobi.com/word-search-classic',
        description: '在字母网格中寻找隐藏的单词，挑战你的词汇量和观察力。这款经典文字游戏适合所有年龄段玩家。',
        rating: 4.5,
        releaseDate: '2023-05-10',
        playCount: 165000,
        isNew: false,
        features: ['多种主题', '不同难度', '词汇学习'],
        tags: ['puzzle', 'word', 'educational']
    },
    {
        id: 'tina-costume-party',
        title: 'Tina Costume Party',
        category: 'casual',
        image: 'img/Tina Costume Party.jpg',
        url: 'https://play.famobi.com/tina-costume-party',
        description: '帮助蒂娜准备一场精彩的化妆舞会，选择主题，装饰场地，设计服装。这款派对游戏充满创意和时尚元素。',
        rating: 4.3,
        releaseDate: '2023-10-25',
        playCount: 128000,
        isNew: true,
        features: ['服装设计', '派对装饰', '角色互动'],
        tags: ['casual', 'dress-up', 'party']
    },
    {
        id: 'nina-costume-party',
        title: 'Nina Costume Party',
        category: 'casual',
        image: 'img/Nina Costume Party.jpg',
        url: 'https://play.famobi.com/nina-costume-party',
        description: '和妮娜一起筹办一场盛大的化妆派对，创造独特服装，邀请朋友，享受派对乐趣。',
        rating: 4.2,
        releaseDate: '2023-10-28',
        playCount: 118000,
        isNew: true,
        features: ['服装创作', '角色扮演', '社交互动'],
        tags: ['casual', 'dress-up', 'party']
    },
    {
        id: 'nina-great-summer-day',
        title: 'Nina Great Summer Day',
        category: 'casual',
        image: 'img/Nina Great Summer Day.jpg',
        url: 'https://play.famobi.com/nina-great-summer-day',
        description: '陪伴妮娜度过完美的夏日，参加沙滩活动，游泳，冲浪，享受阳光。这款夏季游戏充满欢乐和阳光。',
        rating: 4.1,
        releaseDate: '2023-06-30',
        playCount: 95000,
        isNew: false,
        features: ['海滩活动', '夏日装扮', '朋友互动'],
        tags: ['casual', 'summer', 'beach']
    },
    {
        id: 'tina-great-summer-day',
        title: 'Tina Great Summer Day',
        category: 'casual',
        image: 'img/Tina Great Summer Day.jpg',
        url: 'https://play.famobi.com/tina-great-summer-day',
        description: '跟随蒂娜享受阳光明媚的夏日，从早晨的准备到沙滩派对。这款夏季主题游戏让你体验完美假期。',
        rating: 4.2,
        releaseDate: '2023-07-05',
        playCount: 102000,
        isNew: false,
        features: ['假日活动', '夏季时尚', '户外冒险'],
        tags: ['casual', 'summer', 'fashion']
    },
    {
        id: 'street-hoops',
        title: 'Street Hoops',
        category: 'sports',
        image: 'img/Street Hoops.jpg',
        url: 'https://play.famobi.com/street-hoops',
        description: '在街头篮球场展示你的技巧，完成各种花式投篮挑战。这款篮球游戏融合了街头文化和体育竞技。',
        rating: 4.6,
        releaseDate: '2023-09-18',
        playCount: 158000,
        isNew: true,
        features: ['街头风格', '花式技巧', '比赛模式'],
        tags: ['sports', 'basketball', 'urban']
    },
    {
        id: 'square-stacker',
        title: 'Square Stacker',
        category: 'puzzle',
        image: 'img/Square Stacker.jpg',
        url: 'https://play.famobi.com/square-stacker',
        description: '精准堆叠方块，建造尽可能高的塔。这款休闲益智游戏考验你的耐心和时机把握能力。',
        rating: 4.3,
        releaseDate: '2023-08-22',
        playCount: 125000,
        isNew: false,
        features: ['精准控制', '高度挑战', '物理引擎'],
        tags: ['puzzle', 'stacking', 'timing']
    },
    {
        id: 'find',
        title: 'Find',
        category: 'puzzle',
        image: 'img/Find.jpg',
        url: 'https://play.famobi.com/find',
        description: '寻找隐藏在复杂场景中的物品，训练你的观察力和注意力。这款游戏让你沉浸在寻宝的乐趣中。',
        rating: 4.5,
        releaseDate: '2023-07-18',
        playCount: 145000,
        isNew: false,
        features: ['细节观察', '多样场景', '计时挑战'],
        tags: ['puzzle', 'hidden object', 'observation']
    },
    {
        id: 'the-ways',
        title: 'The Ways',
        category: 'adventure',
        image: 'img/The Ways.jpg',
        url: 'https://play.famobi.com/the-ways',
        description: '探索多条人生道路，做出不同的选择，体验各种可能的结局。这款冒险游戏让你思考生活中的决定。',
        rating: 4.4,
        releaseDate: '2023-11-15',
        playCount: 132000,
        isNew: true,
        features: ['多重选择', '故事分支', '角色发展'],
        tags: ['adventure', 'story', 'choices']
    },
    {
        id: 'bffs-house-party',
        title: 'BFFs House Party',
        category: 'casual',
        image: 'img/BFFs House Party.jpg',
        url: 'https://play.famobi.com/bffs-house-party',
        description: '与闺蜜一起举办完美的家庭派对，从装饰、食物到活动，确保每个人都玩得开心。',
        rating: 4.3,
        releaseDate: '2023-09-08',
        playCount: 115000,
        isNew: true,
        features: ['派对策划', '角色互动', '活动组织'],
        tags: ['casual', 'party', 'social']
    },
    {
        id: 'totemia-cursed-marbles',
        title: 'Totemia Cursed Marbles',
        category: 'puzzle',
        image: 'img/Totemia Cursed Marbles.jpg',
        url: 'https://play.famobi.com/totemia-cursed-marbles',
        description: '消除古老神庙中被诅咒的彩球，解开图腾之谜。这款匹配游戏融合了谜题解决和冒险探索。',
        rating: 4.6,
        releaseDate: '2023-08-15',
        playCount: 165000,
        isNew: false,
        features: ['图腾主题', '彩球消除', '特殊能力'],
        tags: ['puzzle', 'match3', 'adventure']
    },
    {
        id: 'mafia-poker',
        title: 'Mafia Poker',
        category: 'puzzle',
        image: 'img/Mafia Poker.jpg',
        url: 'https://play.famobi.com/mafia-poker',
        description: '在黑手党主题的扑克游戏中展示你的牌技，与各种角色对决，赢取赌注。这款纸牌游戏充满紧张气氛。',
        rating: 4.5,
        releaseDate: '2023-10-12',
        playCount: 148000,
        isNew: true,
        features: ['黑帮主题', '扑克技巧', '角色对战'],
        tags: ['puzzle', 'cards', 'poker']
    },
    {
        id: 'tina-airlines',
        title: 'Tina Airlines',
        category: 'simulation',
        image: 'img/Tina Airlines.jpg',
        url: 'https://play.famobi.com/tina-airlines',
        description: '帮助蒂娜经营她的航空公司，从安排航班到服务乘客。这款模拟游戏让你体验航空业的挑战和乐趣。',
        rating: 4.4,
        releaseDate: '2023-09-20',
        playCount: 125000,
        isNew: true,
        features: ['航班管理', '乘客服务', '飞机升级'],
        tags: ['simulation', 'management', 'airline']
    },
    {
        id: 'winter-makeup',
        title: 'Winter Makeup',
        category: 'casual',
        image: 'img/Winter Makeup.jpg',
        url: 'https://play.famobi.com/winter-makeup',
        description: '为模特设计完美的冬季妆容，选择适合冰雪季节的化妆品和风格。这款游戏让你展示美妆创意。',
        rating: 4.3,
        releaseDate: '2023-12-01',
        playCount: 118000,
        isNew: true,
        features: ['化妆技巧', '冬季主题', '时尚搭配'],
        tags: ['casual', 'makeup', 'fashion']
    },
    {
        id: 'jewel-aquarium',
        title: 'Jewel Aquarium',
        category: 'puzzle',
        image: 'img/Jewel Aquarium.jpg',
        url: 'https://play.famobi.com/jewel-aquarium',
        description: '在水族馆主题中匹配宝石和海洋生物，创造海底连锁反应。这款三消游戏融合了海洋美景和益智挑战。',
        rating: 4.5,
        releaseDate: '2023-08-05',
        playCount: 158000,
        isNew: false,
        features: ['海洋主题', '宝石匹配', '特殊能力'],
        tags: ['puzzle', 'match3', 'aquarium']
    },
    {
        id: 'yatzy-classic',
        title: 'Yatzy Classic',
        category: 'puzzle',
        image: 'img/Yatzy Classic.jpg',
        url: 'https://play.famobi.com/yatzy-classic',
        description: '体验这款经典骰子游戏，通过战略性掷骰和组合获得最高分数。这款游戏结合了运气和策略。',
        rating: 4.6,
        releaseDate: '2023-06-22',
        playCount: 168000,
        isNew: false,
        features: ['经典规则', '多人模式', '成就系统'],
        tags: ['puzzle', 'dice', 'strategy']
    },
    {
        id: 'biker-street',
        title: 'Biker Street',
        category: 'racing',
        image: 'img/Biker Street.jpg',
        url: 'https://play.famobi.com/biker-street',
        description: '骑着摩托车穿越繁忙的街道，躲避交通，完成各种挑战。这款赛车游戏测试你的反应速度和驾驶技巧。',
        rating: 4.4,
        releaseDate: '2023-10-08',
        playCount: 142000,
        isNew: true,
        features: ['城市赛道', '摩托升级', '障碍躲避'],
        tags: ['racing', 'motorcycle', 'traffic']
    },
    {
        id: 'angry-flappy-wings',
        title: 'Angry Flappy Wings',
        category: 'action',
        image: 'img/Angry Flappy Wings.jpg',
        url: 'https://play.famobi.com/angry-flappy-wings',
        description: '控制愤怒的小鸟飞越充满障碍的关卡，躲避管道和其他危险。这款动作游戏需要精确的时机和耐心。',
        rating: 4.3,
        releaseDate: '2023-11-28',
        playCount: 155000,
        isNew: true,
        features: ['简单操作', '逐渐增加的难度', '关卡变化'],
        tags: ['action', 'flying', 'arcade']
    }
];

// 处理未分类游戏
function validateGameCategories(games) {
    return games.map(game => {
        if (!game.category) {
            game.category = autoCategorizegame(game);
        }
        return game;
    });
}

// 游戏难度定义
const difficulties = {
    easy: '简单',
    medium: '中等',
    hard: '困难'
};

// 将数据暴露为全局变量
window.gameData = validateGameCategories(gameData);
window.categories = categories;
window.difficulties = difficulties;
