// 游戏分类定义
const categories = {
    action: {
        id: 'action',
        name: '动作游戏',
        icon: '<i class="fas fa-gamepad"></i>',
        keywords: ['action', 'fight', 'battle', 'run', 'jump', 'shooter']
    },
    adventure: {
        id: 'adventure',
        name: '冒险游戏',
        icon: '<i class="fas fa-compass"></i>',
        keywords: ['adventure', 'explore', 'quest', 'journey', 'story']
    },
    puzzle: {
        id: 'puzzle',
        name: '益智游戏',
        icon: '<i class="fas fa-puzzle-piece"></i>',
        keywords: ['puzzle', 'brain', 'logic', 'match', 'solve', 'think']
    },
    strategy: {
        id: 'strategy',
        name: '策略游戏',
        icon: '<i class="fas fa-chess"></i>',
        keywords: ['strategy', 'build', 'manage', 'plan', 'tower']
    },
    sports: {
        id: 'sports',
        name: '体育游戏',
        icon: '<i class="fas fa-futbol"></i>',
        keywords: ['sports', 'ball', 'race', 'soccer', 'basketball']
    },
    racing: {
        id: 'racing',
        name: '赛车游戏',
        icon: '<i class="fas fa-car"></i>',
        keywords: ['racing', 'car', 'drive', 'speed', 'vehicle']
    },
    shooting: {
        id: 'shooting',
        name: '射击游戏',
        icon: '<i class="fas fa-crosshairs"></i>',
        keywords: ['shooting', 'gun', 'sniper', 'aim', 'target']
    },
    casual: {
        id: 'casual',
        name: '休闲游戏',
        icon: '<i class="fas fa-smile"></i>',
        keywords: ['casual', 'simple', 'relax', 'easy', 'fun']
    }
};

// 自动分类函数
function autoCategorizegame(game) {
    // 基于游戏标题、描述和标签进行分类
    const gameText = `${game.title} ${game.description} ${game.tags.join(' ')} ${game.subCategory || ''}`.toLowerCase();
    
    // 记录每个分类的匹配分数
    const scores = {};
    
    // 计算每个分类的匹配度
    Object.entries(categories).forEach(([categoryId, category]) => {
        // 基础分数
        let score = category.keywords.reduce((total, keyword) => {
            const regex = new RegExp(keyword, 'gi');
            const matches = (gameText.match(regex) || []).length;
            return total + matches;
        }, 0);
        
        // 额外规则
        if (game.subCategory) {
            // 子分类匹配加分
            if (category.keywords.some(keyword => game.subCategory.toLowerCase().includes(keyword))) {
                score += 2;
            }
        }
        
        // 特定类型判断
        if (categoryId === 'action' && gameText.includes('combat')) score += 1;
        if (categoryId === 'puzzle' && gameText.includes('solve')) score += 1;
        if (categoryId === 'strategy' && gameText.includes('manage')) score += 1;
        if (categoryId === 'casual' && gameText.includes('relax')) score += 1;
        
        scores[categoryId] = score;
    });
    
    // 找出匹配度最高的分类
    const bestMatch = Object.entries(scores).reduce((best, [categoryId, score]) => {
        return score > best.score ? { categoryId, score } : best;
    }, { categoryId: 'casual', score: 0 });
    
    return bestMatch.score > 0 ? bestMatch.categoryId : 'casual';
}

// 游戏数据
const gameData = [
    {
        id: 'rise-up',
        title: 'Rise Up',
        description: '一个充满挑战的动作游戏，控制气球上升并避开障碍物。',
        tags: ['action', 'arcade', 'balloon', 'obstacle'],
        rating: 4.5,
        difficulty: 'medium',
        playCount: 250000,
        image: 'path/to/rise-up.jpg',
        isNew: true
    },
    {
        id: "giant-rush",
        title: "Giant Rush",
        category: "Action",
        subCategory: "Runner",
        description: "Become a towering giant and rush through the city, growing bigger as you collect power-ups and avoid obstacles. Can you become the biggest giant?",
        rating: 4.7,
        difficulty: "easy",
        playCount: 180000,
        releaseDate: "2023-02-01",
        image: "https://img.cdn.famobi.com/portal/html5games/images/tmp/GiantRushTeaser.jpg",
        url: "https://play.famobi.com/giant-rush",
        tags: ["runner", "giant", "city", "collection"],
        features: ["Endless Runner", "Power-ups", "Character Customization"],
        isFeatured: true,
        isNew: true
    },
    {
        id: "train-miner",
        title: "Train Miner",
        category: "Adventure",
        subCategory: "Mining",
        description: "Dig deep underground with your train, collect valuable resources and upgrade your equipment in this exciting mining adventure.",
        rating: 4.4,
        difficulty: "medium",
        playCount: 120000,
        releaseDate: "2023-01-20",
        image: "https://img.cdn.famobi.com/portal/html5games/images/tmp/TrainMinerTeaser.jpg",
        url: "https://play.famobi.com/train-miner",
        tags: ["mining", "upgrade", "resource", "train"],
        features: ["Upgrades", "Resource Collection", "Progressive Difficulty"]
    },
    {
        id: "western-sniper",
        title: "Western Sniper",
        category: "Action",
        subCategory: "Shooting",
        description: "Take aim in the Wild West as a skilled sniper. Complete challenging missions and prove yourself as the fastest gun in the West.",
        rating: 4.6,
        difficulty: "hard",
        playCount: 200000,
        releaseDate: "2023-02-10",
        image: "https://img.cdn.famobi.com/portal/html5games/images/tmp/WesternSniperTeaser.jpg",
        url: "https://play.famobi.com/western-sniper",
        tags: ["shooting", "western", "sniper", "accuracy"],
        features: ["Multiple Missions", "Weapon Upgrades", "Precision Aiming"]
    },
    {
        id: "go-escape",
        title: "Go Escape",
        category: "Puzzle",
        subCategory: "Escape",
        description: "Use your wit and problem-solving skills to find your way out of increasingly challenging rooms. Every escape requires strategy and quick thinking.",
        rating: 4.3,
        difficulty: "medium",
        playCount: 145000,
        releaseDate: "2023-02-15",
        image: "https://img.cdn.famobi.com/portal/html5games/images/tmp/GoEscapeTeaser.jpg",
        url: "https://play.famobi.com/go-escape",
        tags: ["escape", "puzzle", "logic", "rooms"],
        features: ["Multiple Levels", "Hidden Objects", "Logic Puzzles"]
    },
    {
        id: "color-fill",
        title: "Color Fill",
        category: "Puzzle",
        subCategory: "Coloring",
        description: "Fill the board with colors in this relaxing yet challenging puzzle game. Plan your moves carefully to complete each level.",
        rating: 4.2,
        difficulty: "easy",
        playCount: 168000,
        releaseDate: "2023-03-01",
        image: "https://img.cdn.famobi.com/portal/html5games/images/tmp/ColorFillTeaser.jpg",
        url: "https://play.famobi.com/color-fill",
        tags: ["coloring", "relaxing", "strategy", "puzzle"],
        features: ["Endless Levels", "Color Mechanics", "Progressive Difficulty"]
    },
    {
        id: "spot-the-cat",
        title: "Spot the Cat",
        category: "Puzzle",
        subCategory: "Hidden Object",
        description: "Test your observation skills by finding the hidden cats in various detailed scenes. Each level brings new challenges and cute discoveries.",
        rating: 4.4,
        difficulty: "easy",
        playCount: 132000,
        releaseDate: "2023-03-10",
        image: "https://img.cdn.famobi.com/portal/html5games/images/tmp/SpotTheCatTeaser.jpg",
        url: "https://play.famobi.com/spot-the-cat",
        tags: ["cats", "hidden object", "observation", "cute"],
        features: ["Multiple Scenes", "Time Challenge", "Achievement System"]
    },
    {
        id: "color-roll",
        title: "Color Roll",
        category: "Arcade",
        subCategory: "Rolling",
        description: "Roll through colorful obstacles and collect points in this fast-paced arcade game. Time your moves perfectly to achieve the highest score.",
        rating: 4.5,
        difficulty: "medium",
        playCount: 175000,
        releaseDate: "2023-03-15",
        image: "https://img.cdn.famobi.com/portal/html5games/images/tmp/ColorRollTeaser.jpg",
        url: "https://play.famobi.com/color-roll",
        tags: ["rolling", "arcade", "colorful", "fast-paced"],
        features: ["Score System", "Power-ups", "Dynamic Obstacles"]
    },
    {
        id: "color-water-sort",
        title: "Color Water Sort",
        category: "Puzzle",
        subCategory: "Sorting",
        description: "Sort colored water in tubes using logic and strategy. A relaxing yet challenging puzzle game that tests your problem-solving skills.",
        rating: 4.7,
        difficulty: "medium",
        playCount: 220000,
        releaseDate: "2023-03-20",
        image: "https://img.cdn.famobi.com/portal/html5games/images/tmp/ColorWaterSortTeaser.jpg",
        url: "https://play.famobi.com/color-water-sort",
        tags: ["sorting", "logic", "relaxing", "strategy"],
        features: ["Unlimited Levels", "Undo Move", "Hint System"]
    },
    {
        id: "braindom",
        title: "Braindom",
        category: "Puzzle",
        subCategory: "Brain Teaser",
        description: "Challenge your mind with unique and creative puzzles. Each level presents a new type of problem that requires thinking outside the box.",
        rating: 4.6,
        difficulty: "hard",
        playCount: 190000,
        releaseDate: "2023-03-25",
        image: "https://img.cdn.famobi.com/portal/html5games/images/tmp/BraindomTeaser.jpg",
        url: "https://play.famobi.com/braindom",
        tags: ["brain teaser", "logic", "creative", "thinking"],
        features: ["Diverse Puzzles", "Hint System", "Achievement Badges"]
    },
    {
        id: "sort-it",
        title: "Sort It",
        category: "Puzzle",
        subCategory: "Sorting",
        description: "Sort various objects into their correct categories in this addictive puzzle game. Quick thinking and organization skills are key to success.",
        rating: 4.3,
        difficulty: "medium",
        playCount: 165000,
        releaseDate: "2023-04-01",
        image: "https://img.cdn.famobi.com/portal/html5games/images/tmp/SortItTeaser.jpg",
        url: "https://play.famobi.com/sort-it",
        tags: ["sorting", "organization", "quick thinking", "categories"],
        features: ["Multiple Categories", "Time Challenge", "Progress Tracking"]
    },
    {
        id: "cube-match",
        title: "Cube Match",
        category: "Puzzle",
        subCategory: "Matching",
        description: "Match colorful cubes in this 3D puzzle game. Rotate the view and plan your moves carefully to clear all cubes from the board.",
        rating: 4.4,
        difficulty: "medium",
        playCount: 155000,
        releaseDate: "2023-04-05",
        image: "https://img.cdn.famobi.com/portal/html5games/images/tmp/CubeMatchTeaser.jpg",
        url: "https://play.famobi.com/cube-match",
        tags: ["3D", "matching", "rotation", "strategy"],
        features: ["3D Rotation", "Multiple Levels", "Special Cubes"]
    },
    {
        id: "parking-jam",
        title: "Parking Jam",
        category: "Puzzle",
        subCategory: "Vehicle",
        description: "Solve challenging parking puzzles by moving cars and clearing the way. Test your spatial thinking and planning skills in increasingly complex scenarios.",
        rating: 4.5,
        difficulty: "medium",
        playCount: 185000,
        releaseDate: "2023-04-10",
        image: "https://img.cdn.famobi.com/portal/html5games/images/tmp/ParkingJamTeaser.jpg",
        url: "https://play.famobi.com/parking-jam",
        tags: ["parking", "cars", "logic", "spatial"],
        features: ["Level Editor", "Progressive Difficulty", "Achievement System"]
    },
    {
        id: "fashion-battle",
        title: "Fashion Battle",
        category: "Casual",
        subCategory: "Fashion",
        description: "Compete in fashion challenges, create stunning outfits, and become a style icon. Mix and match different clothing items to win fashion battles.",
        rating: 4.3,
        difficulty: "easy",
        playCount: 210000,
        releaseDate: "2023-04-15",
        image: "https://img.cdn.famobi.com/portal/html5games/images/tmp/FashionBattleTeaser.jpg",
        url: "https://play.famobi.com/fashion-battle",
        tags: ["fashion", "dress-up", "competition", "style"],
        features: ["Customization", "Multiplayer Battles", "Fashion Collections"]
    },
    {
        id: "fruit-party",
        title: "Fruit Party",
        category: "Arcade",
        subCategory: "Matching",
        description: "Join the fruity fun in this colorful matching game. Connect same fruits to create delicious combinations and trigger exciting chain reactions.",
        rating: 4.6,
        difficulty: "easy",
        playCount: 195000,
        releaseDate: "2023-04-20",
        image: "https://img.cdn.famobi.com/portal/html5games/images/tmp/FruitPartyTeaser.jpg",
        url: "https://play.famobi.com/fruit-party",
        tags: ["fruits", "matching", "colorful", "chain-reaction"],
        features: ["Power-ups", "Special Combinations", "Daily Challenges"]
    },
    {
        id: "thief-puzzle",
        title: "Thief Puzzle",
        category: "Puzzle",
        subCategory: "Stealth",
        description: "Plan the perfect heist by solving challenging stealth puzzles. Use your wit to avoid security systems and collect treasures.",
        rating: 4.7,
        difficulty: "hard",
        playCount: 165000,
        releaseDate: "2023-04-25",
        image: "https://img.cdn.famobi.com/portal/html5games/images/tmp/ThiefPuzzleTeaser.jpg",
        url: "https://play.famobi.com/thief-puzzle",
        tags: ["stealth", "strategy", "heist", "puzzle"],
        features: ["Multiple Solutions", "Security Systems", "Special Tools"]
    },
    {
        id: "guess-their-answer",
        title: "Guess Their Answer",
        category: "Puzzle",
        subCategory: "Quiz",
        description: "Test your ability to predict how others would answer various questions. A unique social psychology game that's both fun and insightful.",
        rating: 4.4,
        difficulty: "medium",
        playCount: 175000,
        releaseDate: "2023-05-01",
        image: "https://img.cdn.famobi.com/portal/html5games/images/tmp/GuessTheirAnswerTeaser.jpg",
        url: "https://play.famobi.com/guess-their-answer",
        tags: ["quiz", "psychology", "social", "thinking"],
        features: ["Statistics", "Social Sharing", "Daily Questions"]
    },
    {
        id: "neon-rider",
        title: "Neon Rider",
        category: "Action",
        subCategory: "Racing",
        description: "Race through neon-lit tracks in this high-speed motorcycle game. Master the controls and timing to achieve the perfect run.",
        rating: 4.8,
        difficulty: "hard",
        playCount: 225000,
        releaseDate: "2023-05-05",
        image: "https://img.cdn.famobi.com/portal/html5games/images/tmp/NeonRiderTeaser.jpg",
        url: "https://play.famobi.com/neon-rider",
        tags: ["racing", "neon", "motorcycle", "speed"],
        features: ["Multiple Tracks", "Bike Upgrades", "Time Trials"]
    },
    {
        id: "speed-master",
        title: "Speed Master",
        category: "Action",
        subCategory: "Racing",
        description: "Push your reflexes to the limit in this fast-paced racing game. Navigate through traffic and obstacles while maintaining top speed.",
        rating: 4.5,
        difficulty: "medium",
        playCount: 195000,
        releaseDate: "2023-05-10",
        image: "https://img.cdn.famobi.com/portal/html5games/images/tmp/SpeedMasterTeaser.jpg",
        url: "https://play.famobi.com/speed-master",
        tags: ["racing", "speed", "traffic", "reflexes"],
        features: ["Career Mode", "Vehicle Collection", "Daily Challenges"]
    },
    {
        id: "alien-attack",
        title: "Alien Attack",
        category: "Action",
        subCategory: "Shooting",
        description: "Defend Earth from waves of alien invaders in this classic arcade-style shooter. Upgrade your weapons and face increasingly challenging enemies.",
        rating: 4.6,
        difficulty: "medium",
        playCount: 185000,
        releaseDate: "2023-05-15",
        image: "https://img.cdn.famobi.com/portal/html5games/images/tmp/AlienAttackTeaser.jpg",
        url: "https://play.famobi.com/alien-attack",
        tags: ["aliens", "shooting", "space", "arcade"],
        features: ["Weapon Upgrades", "Boss Battles", "Power-ups"]
    },
    {
        id: "peet-sneak",
        title: "Peet Sneak",
        category: "Adventure",
        subCategory: "Stealth",
        description: "Help Peet sneak past various obstacles and guards in this charming stealth game. Use timing and strategy to complete each level undetected.",
        rating: 4.4,
        difficulty: "medium",
        playCount: 155000,
        releaseDate: "2023-05-20",
        image: "https://img.cdn.famobi.com/portal/html5games/images/tmp/PeetSneakTeaser.jpg",
        url: "https://play.famobi.com/peet-sneak",
        tags: ["stealth", "cute", "strategy", "timing"],
        features: ["Multiple Characters", "Special Abilities", "Hidden Collectibles"]
    },
    {
        id: "cut-the-rope",
        title: "Cut the Rope",
        category: "Puzzle",
        subCategory: "Physics",
        description: "Feed the cute monster Om Nom by cutting ropes at the right moment. Use physics and timing to solve increasingly challenging candy-delivery puzzles.",
        rating: 4.9,
        difficulty: "medium",
        playCount: 300000,
        releaseDate: "2023-05-25",
        image: "https://img.cdn.famobi.com/portal/html5games/images/tmp/CutTheRopeTeaser.jpg",
        url: "https://play.famobi.com/cut-the-rope",
        tags: ["physics", "cute", "puzzle", "timing"],
        features: ["Physics Engine", "Star Collection", "Special Candies"]
    },
    {
        id: "toilet-run",
        title: "Toilet Run",
        category: "Arcade",
        subCategory: "Runner",
        description: "Race through quirky obstacles in this humorous endless runner. Time your moves perfectly to avoid obstacles and collect power-ups.",
        rating: 4.3,
        difficulty: "easy",
        playCount: 165000,
        releaseDate: "2023-06-01",
        image: "https://img.cdn.famobi.com/portal/html5games/images/tmp/ToiletRunTeaser.jpg",
        url: "https://play.famobi.com/toilet-run",
        tags: ["funny", "runner", "arcade", "casual"],
        features: ["Endless Mode", "Character Customization", "Power-ups"]
    },
    {
        id: "block-painter",
        title: "Block Painter",
        category: "Puzzle",
        subCategory: "Coloring",
        description: "Paint blocks with strategic moves to create beautiful patterns. Each level presents new challenges and color combinations to master.",
        rating: 4.5,
        difficulty: "medium",
        playCount: 145000,
        releaseDate: "2023-06-05",
        image: "https://img.cdn.famobi.com/portal/html5games/images/tmp/BlockPainterTeaser.jpg",
        url: "https://play.famobi.com/block-painter",
        tags: ["painting", "strategy", "relaxing", "patterns"],
        features: ["Level Creator", "Color Challenges", "Achievement System"]
    },
    {
        id: "cowboy-swing",
        title: "Cowboy Swing",
        category: "Action",
        subCategory: "Adventure",
        description: "Swing through the Wild West as a daring cowboy. Master the rope mechanics and timing to overcome challenging obstacles.",
        rating: 4.6,
        difficulty: "medium",
        playCount: 175000,
        releaseDate: "2023-06-10",
        image: "https://img.cdn.famobi.com/portal/html5games/images/tmp/CowboySwingTeaser.jpg",
        url: "https://play.famobi.com/cowboy-swing",
        tags: ["western", "swinging", "adventure", "timing"],
        features: ["Physics Based", "Character Upgrades", "Hidden Treasures"]
    },
    {
        id: "pair-up",
        title: "Pair Up",
        category: "Puzzle",
        subCategory: "Matching",
        description: "Match pairs of cards in this memory-testing puzzle game. Different themes and increasing difficulty keep the challenge fresh.",
        rating: 4.4,
        difficulty: "easy",
        playCount: 190000,
        releaseDate: "2023-06-15",
        image: "https://img.cdn.famobi.com/portal/html5games/images/tmp/PairUpTeaser.jpg",
        url: "https://play.famobi.com/pair-up",
        tags: ["memory", "matching", "cards", "brain training"],
        features: ["Multiple Themes", "Time Challenge", "Leaderboards"]
    },
    {
        id: "go-around",
        title: "Go Around",
        category: "Arcade",
        subCategory: "Skill",
        description: "Navigate through rotating obstacles in this challenging arcade game. Test your timing and reflexes as you progress through levels.",
        rating: 4.7,
        difficulty: "hard",
        playCount: 160000,
        releaseDate: "2023-06-20",
        image: "https://img.cdn.famobi.com/portal/html5games/images/tmp/GoAroundTeaser.jpg",
        url: "https://play.famobi.com/go-around",
        tags: ["timing", "reflexes", "arcade", "challenging"],
        features: ["Progressive Difficulty", "Special Modes", "Global Rankings"]
    },
    {
        id: "green-ball",
        title: "Green Ball",
        category: "Puzzle",
        subCategory: "Physics",
        description: "Guide the green ball through physics-based puzzles. Use gravity and various mechanics to reach the goal in each level.",
        rating: 4.5,
        difficulty: "medium",
        playCount: 170000,
        releaseDate: "2023-06-25",
        image: "https://img.cdn.famobi.com/portal/html5games/images/tmp/GreenBallTeaser.jpg",
        url: "https://play.famobi.com/green-ball",
        tags: ["physics", "ball", "puzzle", "gravity"],
        features: ["Physics Engine", "Level Editor", "Achievement System"]
    },
    {
        id: "twisty-lines",
        title: "Twisty Lines",
        category: "Puzzle",
        subCategory: "Line Drawing",
        description: "Connect dots with twisting lines in this mesmerizing puzzle game. Create beautiful patterns while solving challenging levels.",
        rating: 4.6,
        difficulty: "medium",
        playCount: 155000,
        releaseDate: "2023-07-01",
        image: "https://img.cdn.famobi.com/portal/html5games/images/tmp/TwistyLinesTeaser.jpg",
        url: "https://play.famobi.com/twisty-lines",
        tags: ["lines", "patterns", "relaxing", "artistic"],
        features: ["Endless Mode", "Pattern Creation", "Color Themes"]
    },
    {
        id: "lawn-mower",
        title: "Lawn Mower",
        category: "Simulation",
        subCategory: "Management",
        description: "Mow lawns and grow your landscaping business. Upgrade equipment and tackle increasingly challenging yards.",
        rating: 4.3,
        difficulty: "easy",
        playCount: 145000,
        releaseDate: "2023-07-05",
        image: "https://img.cdn.famobi.com/portal/html5games/images/tmp/LawnMowerTeaser.jpg",
        url: "https://play.famobi.com/lawn-mower",
        tags: ["simulation", "management", "upgrade", "relaxing"],
        features: ["Business Management", "Equipment Upgrades", "Customer Satisfaction"]
    },
    {
        id: "rising-squares",
        title: "Rising Squares",
        category: "Arcade",
        subCategory: "Platformer",
        description: "Jump between rising platforms in this fast-paced arcade game. Time your moves perfectly to avoid falling and reach new heights.",
        rating: 4.5,
        difficulty: "hard",
        playCount: 180000,
        releaseDate: "2023-07-10",
        image: "https://img.cdn.famobi.com/portal/html5games/images/tmp/RisingSquaresTeaser.jpg",
        url: "https://play.famobi.com/rising-squares",
        tags: ["platformer", "jumping", "timing", "arcade"],
        features: ["High Score System", "Power-ups", "Different Modes"]
    },
    {
        id: "tower-fall",
        title: "Tower Fall",
        category: "Action",
        subCategory: "Destruction",
        description: "Destroy towers with precise shots in this physics-based destruction game. Calculate angles and power to achieve maximum damage.",
        rating: 4.7,
        difficulty: "medium",
        playCount: 195000,
        releaseDate: "2023-07-15",
        image: "https://img.cdn.famobi.com/portal/html5games/images/tmp/TowerFallTeaser.jpg",
        url: "https://play.famobi.com/tower-fall",
        tags: ["physics", "destruction", "strategy", "aiming"],
        features: ["Physics Engine", "Multiple Weapons", "Challenge Modes"]
    },
    {
        id: "emoji-fun",
        title: "Emoji Fun",
        category: "Casual",
        subCategory: "Matching",
        description: "Match emojis in this colorful and entertaining puzzle game. Create combinations and trigger special effects for higher scores.",
        rating: 4.4,
        difficulty: "easy",
        playCount: 170000,
        releaseDate: "2023-07-20",
        image: "https://img.cdn.famobi.com/portal/html5games/images/tmp/EmojiFunTeaser.jpg",
        url: "https://play.famobi.com/emoji-fun",
        tags: ["emoji", "matching", "casual", "colorful"],
        features: ["Special Combinations", "Daily Challenges", "Social Sharing"]
    },
    {
        id: "bottle-flip",
        title: "Bottle Flip",
        category: "Arcade",
        subCategory: "Skill",
        description: "Master the art of bottle flipping in this addictive skill game. Perfect your timing and technique to perform amazing tricks.",
        rating: 4.5,
        difficulty: "medium",
        playCount: 210000,
        releaseDate: "2023-07-25",
        image: "https://img.cdn.famobi.com/portal/html5games/images/tmp/BottleFlipTeaser.jpg",
        url: "https://play.famobi.com/bottle-flip",
        tags: ["skill", "flipping", "tricks", "physics"],
        features: ["Trick System", "Different Bottles", "Challenge Mode"]
    },
    {
        id: "color-match",
        title: "Color Match",
        category: "Puzzle",
        subCategory: "Matching",
        description: "Match and combine colors in this engaging puzzle game. Create beautiful patterns while solving increasingly challenging levels.",
        rating: 4.4,
        difficulty: "easy",
        playCount: 185000,
        releaseDate: "2023-08-01",
        image: "https://img.cdn.famobi.com/portal/html5games/images/tmp/ColorMatchTeaser.jpg",
        url: "https://play.famobi.com/color-match",
        tags: ["colors", "matching", "puzzle", "relaxing"],
        features: ["Color Combinations", "Pattern Creation", "Daily Challenges"]
    },
    {
        id: "ninja-run",
        title: "Ninja Run",
        category: "Action",
        subCategory: "Runner",
        description: "Run and jump through ancient Japanese landscapes as a skilled ninja. Collect power-ups and avoid obstacles in this fast-paced adventure.",
        rating: 4.6,
        difficulty: "medium",
        playCount: 195000,
        releaseDate: "2023-08-05",
        image: "https://img.cdn.famobi.com/portal/html5games/images/tmp/NinjaRunTeaser.jpg",
        url: "https://play.famobi.com/ninja-run",
        tags: ["ninja", "runner", "action", "adventure"],
        features: ["Character Upgrades", "Special Abilities", "Achievement System"]
    },
    {
        id: "word-search",
        title: "Word Search",
        category: "Puzzle",
        subCategory: "Word",
        description: "Find hidden words in this classic word search puzzle game. Multiple themes and difficulty levels provide endless entertainment.",
        rating: 4.3,
        difficulty: "easy",
        playCount: 175000,
        releaseDate: "2023-08-10",
        image: "https://img.cdn.famobi.com/portal/html5games/images/tmp/WordSearchTeaser.jpg",
        url: "https://play.famobi.com/word-search",
        tags: ["words", "search", "puzzle", "brain training"],
        features: ["Multiple Themes", "Hint System", "Daily Puzzles"]
    },
    {
        id: "space-shooter",
        title: "Space Shooter",
        category: "Action",
        subCategory: "Shooting",
        description: "Defend the galaxy in this classic space shooter. Upgrade your ship and face waves of alien enemies in epic battles.",
        rating: 4.7,
        difficulty: "medium",
        playCount: 220000,
        releaseDate: "2023-08-15",
        image: "https://img.cdn.famobi.com/portal/html5games/images/tmp/SpaceShooterTeaser.jpg",
        url: "https://play.famobi.com/space-shooter",
        tags: ["space", "shooting", "arcade", "action"],
        features: ["Ship Upgrades", "Boss Battles", "Power-ups"]
    },
    {
        id: "puzzle-box",
        title: "Puzzle Box",
        category: "Puzzle",
        subCategory: "Logic",
        description: "Solve intricate box puzzles by sliding and rotating pieces. Each level presents a new challenge to unlock the box.",
        rating: 4.5,
        difficulty: "hard",
        playCount: 160000,
        releaseDate: "2023-08-20",
        image: "https://img.cdn.famobi.com/portal/html5games/images/tmp/PuzzleBoxTeaser.jpg",
        url: "https://play.famobi.com/puzzle-box",
        tags: ["logic", "puzzle", "box", "challenging"],
        features: ["Multiple Solutions", "Hint System", "Level Editor"]
    },
    {
        id: "farm-frenzy",
        title: "Farm Frenzy",
        category: "Simulation",
        subCategory: "Management",
        description: "Build and manage your own farm in this addictive simulation game. Grow crops, raise animals, and expand your agricultural empire.",
        rating: 4.6,
        difficulty: "medium",
        playCount: 190000,
        releaseDate: "2023-08-25",
        image: "https://img.cdn.famobi.com/portal/html5games/images/tmp/FarmFrenzyTeaser.jpg",
        url: "https://play.famobi.com/farm-frenzy",
        tags: ["farming", "simulation", "management", "relaxing"],
        features: ["Crop System", "Animal Care", "Market Trading"]
    },
    {
        id: "math-master",
        title: "Math Master",
        category: "Puzzle",
        subCategory: "Educational",
        description: "Challenge your mathematical skills in this educational puzzle game. Solve equations and improve your problem-solving abilities.",
        rating: 4.4,
        difficulty: "medium",
        playCount: 170000,
        releaseDate: "2023-09-01",
        image: "https://img.cdn.famobi.com/portal/html5games/images/tmp/MathMasterTeaser.jpg",
        url: "https://play.famobi.com/math-master",
        tags: ["math", "educational", "puzzle", "brain training"],
        features: ["Multiple Operations", "Difficulty Levels", "Progress Tracking"]
    },
    {
        id: "zombie-defense",
        title: "Zombie Defense",
        category: "Action",
        subCategory: "Strategy",
        description: "Defend your base from waves of zombies in this strategic tower defense game. Build defenses and upgrade your weapons to survive.",
        rating: 4.7,
        difficulty: "hard",
        playCount: 205000,
        releaseDate: "2023-09-05",
        image: "https://img.cdn.famobi.com/portal/html5games/images/tmp/ZombieDefenseTeaser.jpg",
        url: "https://play.famobi.com/zombie-defense",
        tags: ["zombies", "defense", "strategy", "action"],
        features: ["Tower System", "Resource Management", "Wave Mode"]
    },
    {
        id: "memory-match",
        title: "Memory Match",
        category: "Puzzle",
        subCategory: "Memory",
        description: "Test your memory by matching pairs of cards in this classic memory game. Multiple themes and difficulty levels provide endless fun.",
        rating: 4.3,
        difficulty: "easy",
        playCount: 180000,
        releaseDate: "2023-09-10",
        image: "https://img.cdn.famobi.com/portal/html5games/images/tmp/MemoryMatchTeaser.jpg",
        url: "https://play.famobi.com/memory-match",
        tags: ["memory", "matching", "cards", "brain training"],
        features: ["Multiple Themes", "Time Challenge", "Score System"]
    },
    {
        id: "candy-crush",
        title: "Candy Crush",
        category: "Puzzle",
        subCategory: "Matching",
        description: "Match colorful candies in this addictive puzzle game. Create special combinations and clear the board to progress through levels.",
        rating: 4.8,
        difficulty: "medium",
        playCount: 250000,
        releaseDate: "2023-09-15",
        image: "https://img.cdn.famobi.com/portal/html5games/images/tmp/CandyCrushTeaser.jpg",
        url: "https://play.famobi.com/candy-crush",
        tags: ["candy", "matching", "puzzle", "colorful"],
        features: ["Special Candies", "Level Progression", "Power-ups"]
    },
    {
        id: "subway-surfers",
        title: "Subway Surfers",
        category: "Action",
        subCategory: "Runner",
        description: "Run through subway tracks, dodge obstacles, and collect coins in this endless runner game. Upgrade your character and unlock new locations.",
        rating: 4.7,
        difficulty: "medium",
        playCount: 280000,
        releaseDate: "2023-09-20",
        image: "https://img.cdn.famobi.com/portal/html5games/images/tmp/SubwaySurfersTeaser.jpg",
        url: "https://play.famobi.com/subway-surfers",
        tags: ["runner", "action", "adventure", "collection"],
        features: ["Character Customization", "Power-ups", "Global Rankings"]
    },
    {
        id: "angry-birds",
        title: "Angry Birds",
        category: "Action",
        subCategory: "Physics",
        description: "Launch angry birds at structures to defeat the green pigs. Use physics and strategy to solve increasingly challenging levels.",
        rating: 4.9,
        difficulty: "medium",
        playCount: 300000,
        releaseDate: "2023-09-25",
        image: "https://img.cdn.famobi.com/portal/html5games/images/tmp/AngryBirdsTeaser.jpg",
        url: "https://play.famobi.com/angry-birds",
        tags: ["physics", "birds", "puzzle", "action"],
        features: ["Multiple Birds", "Star System", "Level Editor"]
    },
    {
        id: "2048",
        title: "2048",
        category: "Puzzle",
        subCategory: "Logic",
        description: "Combine numbered tiles to reach the 2048 tile in this addictive puzzle game. Use strategy and planning to achieve the highest score.",
        rating: 4.6,
        difficulty: "hard",
        playCount: 200000,
        releaseDate: "2023-10-01",
        image: "https://img.cdn.famobi.com/portal/html5games/images/tmp/2048Teaser.jpg",
        url: "https://play.famobi.com/2048",
        tags: ["numbers", "puzzle", "strategy", "brain training"],
        features: ["Score Tracking", "Undo Move", "Achievement System"]
    },
    {
        id: "tetris",
        title: "Tetris",
        category: "Puzzle",
        subCategory: "Classic",
        description: "Arrange falling blocks to create complete lines in this timeless puzzle game. Test your speed and strategy as the blocks fall faster.",
        rating: 4.8,
        difficulty: "medium",
        playCount: 270000,
        releaseDate: "2023-10-05",
        image: "https://img.cdn.famobi.com/portal/html5games/images/tmp/TetrisTeaser.jpg",
        url: "https://play.famobi.com/tetris",
        tags: ["classic", "puzzle", "blocks", "arcade"],
        features: ["Next Piece Preview", "Hold Piece", "Ghost Piece"]
    },
    {
        id: "snake",
        title: "Snake",
        category: "Arcade",
        subCategory: "Classic",
        description: "Control a growing snake and collect food while avoiding walls and yourself in this classic arcade game. Challenge your reflexes and planning.",
        rating: 4.5,
        difficulty: "medium",
        playCount: 220000,
        releaseDate: "2023-10-10",
        image: "https://img.cdn.famobi.com/portal/html5games/images/tmp/SnakeTeaser.jpg",
        url: "https://play.famobi.com/snake",
        tags: ["classic", "arcade", "snake", "retro"],
        features: ["High Score System", "Different Modes", "Power-ups"]
    },
    {
        id: "pac-man",
        title: "Pac-Man",
        category: "Arcade",
        subCategory: "Classic",
        description: "Guide Pac-Man through mazes, collect dots, and avoid ghosts in this iconic arcade game. Use power pellets to turn the tables on your pursuers.",
        rating: 4.7,
        difficulty: "medium",
        playCount: 240000,
        releaseDate: "2023-10-15",
        image: "https://img.cdn.famobi.com/portal/html5games/images/tmp/PacManTeaser.jpg",
        url: "https://play.famobi.com/pac-man",
        tags: ["classic", "arcade", "maze", "retro"],
        features: ["Multiple Levels", "Ghost AI", "Score System"]
    },
    {
        id: "minesweeper",
        title: "Minesweeper",
        category: "Puzzle",
        subCategory: "Logic",
        description: "Find all the mines without triggering them in this classic logic puzzle game. Use numbers as clues to determine safe squares.",
        rating: 4.4,
        difficulty: "hard",
        playCount: 180000,
        releaseDate: "2023-10-20",
        image: "https://img.cdn.famobi.com/portal/html5games/images/tmp/MinesweeperTeaser.jpg",
        url: "https://play.famobi.com/minesweeper",
        tags: ["logic", "puzzle", "classic", "brain training"],
        features: ["Multiple Difficulties", "First Click Safe", "Timer System"]
    },
    {
        id: "sudoku",
        title: "Sudoku",
        category: "Puzzle",
        subCategory: "Logic",
        description: "Fill the grid with numbers following Sudoku rules in this classic number puzzle game. Multiple difficulty levels provide endless challenges.",
        rating: 4.6,
        difficulty: "medium",
        playCount: 210000,
        releaseDate: "2023-10-25",
        image: "https://img.cdn.famobi.com/portal/html5games/images/tmp/SudokuTeaser.jpg",
        url: "https://play.famobi.com/sudoku",
        tags: ["numbers", "puzzle", "logic", "brain training"],
        features: ["Hint System", "Multiple Themes", "Daily Puzzles"]
    },
    {
        id: "crossword-puzzle",
        title: "Crossword Puzzle",
        category: "Puzzle",
        subCategory: "Word",
        description: "Solve crossword puzzles with increasing difficulty. Test your vocabulary and knowledge across various themes and categories.",
        rating: 4.5,
        difficulty: "medium",
        playCount: 195000,
        releaseDate: "2023-11-01",
        image: "https://img.cdn.famobi.com/portal/html5games/images/tmp/CrosswordPuzzleTeaser.jpg",
        url: "https://play.famobi.com/crossword-puzzle",
        tags: ["words", "puzzle", "crossword", "brain training"],
        features: ["Daily Puzzles", "Hint System", "Multiple Categories"]
    },
    {
        id: "chess",
        title: "Chess",
        category: "Strategy",
        subCategory: "Board",
        description: "Play the classic game of chess against AI opponents. Learn strategies and improve your skills with different difficulty levels.",
        rating: 4.8,
        difficulty: "hard",
        playCount: 230000,
        releaseDate: "2023-11-05",
        image: "https://img.cdn.famobi.com/portal/html5games/images/tmp/ChessTeaser.jpg",
        url: "https://play.famobi.com/chess",
        tags: ["chess", "strategy", "board", "classic"],
        features: ["AI Opponents", "Tutorial Mode", "Game Analysis"]
    },
    {
        id: "checkers",
        title: "Checkers",
        category: "Strategy",
        subCategory: "Board",
        description: "Play the classic game of checkers with multiple AI opponents. Master the rules and develop winning strategies.",
        rating: 4.4,
        difficulty: "medium",
        playCount: 185000,
        releaseDate: "2023-11-10",
        image: "https://img.cdn.famobi.com/portal/html5games/images/tmp/CheckersTeaser.jpg",
        url: "https://play.famobi.com/checkers",
        tags: ["checkers", "strategy", "board", "classic"],
        features: ["Multiple AI Levels", "Tutorial", "Statistics"]
    },
    {
        id: "connect-four",
        title: "Connect Four",
        category: "Strategy",
        subCategory: "Board",
        description: "Play the classic Connect Four game against AI or friends. Plan your moves to create a line of four pieces.",
        rating: 4.3,
        difficulty: "medium",
        playCount: 175000,
        releaseDate: "2023-11-15",
        image: "https://img.cdn.famobi.com/portal/html5games/images/tmp/ConnectFourTeaser.jpg",
        url: "https://play.famobi.com/connect-four",
        tags: ["strategy", "board", "classic", "multiplayer"],
        features: ["AI Opponents", "Multiplayer Mode", "Statistics"]
    },
    {
        id: "tictactoe",
        title: "Tic Tac Toe",
        category: "Strategy",
        subCategory: "Board",
        description: "Play the classic Tic Tac Toe game with AI or friends. Perfect for quick games and strategy practice.",
        rating: 4.2,
        difficulty: "easy",
        playCount: 165000,
        releaseDate: "2023-11-20",
        image: "https://img.cdn.famobi.com/portal/html5games/images/tmp/TicTacToeTeaser.jpg",
        url: "https://play.famobi.com/tictactoe",
        tags: ["strategy", "board", "classic", "multiplayer"],
        features: ["AI Opponents", "Multiplayer Mode", "Statistics"]
    },
    {
        id: "hangman",
        title: "Hangman",
        category: "Puzzle",
        subCategory: "Word",
        description: "Guess the word letter by letter in this classic word game. Test your vocabulary and avoid the hangman.",
        rating: 4.3,
        difficulty: "medium",
        playCount: 170000,
        releaseDate: "2023-11-25",
        image: "https://img.cdn.famobi.com/portal/html5games/images/tmp/HangmanTeaser.jpg",
        url: "https://play.famobi.com/hangman",
        tags: ["words", "puzzle", "classic", "vocabulary"],
        features: ["Multiple Categories", "Hint System", "Statistics"]
    },
    {
        id: "scrabble",
        title: "Scrabble",
        category: "Puzzle",
        subCategory: "Word",
        description: "Create words and score points in this classic word game. Challenge your vocabulary and strategic thinking.",
        rating: 4.6,
        difficulty: "hard",
        playCount: 190000,
        releaseDate: "2023-12-01",
        image: "https://img.cdn.famobi.com/portal/html5games/images/tmp/ScrabbleTeaser.jpg",
        url: "https://play.famobi.com/scrabble",
        tags: ["words", "puzzle", "strategy", "vocabulary"],
        features: ["AI Opponents", "Word Checker", "Statistics"]
    },
    {
        id: "boggle",
        title: "Boggle",
        category: "Puzzle",
        subCategory: "Word",
        description: "Find words in a grid of letters in this fast-paced word game. Race against time to find the most words.",
        rating: 4.4,
        difficulty: "medium",
        playCount: 180000,
        releaseDate: "2023-12-05",
        image: "https://img.cdn.famobi.com/portal/html5games/images/tmp/BoggleTeaser.jpg",
        url: "https://play.famobi.com/boggle",
        tags: ["words", "puzzle", "fast-paced", "vocabulary"],
        features: ["Time Mode", "Word Checker", "Statistics"]
    },
    {
        id: "word-ladder",
        title: "Word Ladder",
        category: "Puzzle",
        subCategory: "Word",
        description: "Transform one word into another by changing one letter at a time. Challenge your vocabulary and problem-solving skills.",
        rating: 4.5,
        difficulty: "hard",
        playCount: 160000,
        releaseDate: "2023-12-10",
        image: "https://img.cdn.famobi.com/portal/html5games/images/tmp/WordLadderTeaser.jpg",
        url: "https://play.famobi.com/word-ladder",
        tags: ["words", "puzzle", "logic", "vocabulary"],
        features: ["Multiple Levels", "Hint System", "Statistics"]
    },
    {
        id: "monster-truck",
        title: "Monster Truck",
        category: "Action",
        subCategory: "Racing",
        description: "Drive powerful monster trucks through challenging tracks. Perform stunts and compete in exciting races.",
        rating: 4.6,
        difficulty: "medium",
        playCount: 195000,
        releaseDate: "2023-12-15",
        image: "https://img.cdn.famobi.com/portal/html5games/images/tmp/MonsterTruckTeaser.jpg",
        url: "https://play.famobi.com/monster-truck",
        tags: ["racing", "monster truck", "stunts", "action"],
        features: ["Multiple Trucks", "Track Editor", "Stunt Mode"]
    },
    {
        id: "bubble-shooter",
        title: "Bubble Shooter",
        category: "Puzzle",
        subCategory: "Matching",
        description: "Shoot and match colorful bubbles in this addictive puzzle game. Clear the board by creating groups of matching bubbles.",
        rating: 4.5,
        difficulty: "easy",
        playCount: 210000,
        releaseDate: "2023-12-20",
        image: "https://img.cdn.famobi.com/portal/html5games/images/tmp/BubbleShooterTeaser.jpg",
        url: "https://play.famobi.com/bubble-shooter",
        tags: ["bubbles", "matching", "puzzle", "colorful"],
        features: ["Power-ups", "Special Bubbles", "Level Progression"]
    },
    {
        id: "jewel-match",
        title: "Jewel Match",
        category: "Puzzle",
        subCategory: "Matching",
        description: "Match sparkling jewels in this dazzling puzzle game. Create special combinations to clear the board and collect treasures.",
        rating: 4.7,
        difficulty: "medium",
        playCount: 225000,
        releaseDate: "2023-12-25",
        image: "https://img.cdn.famobi.com/portal/html5games/images/tmp/JewelMatchTeaser.jpg",
        url: "https://play.famobi.com/jewel-match",
        tags: ["jewels", "matching", "puzzle", "sparkling"],
        features: ["Special Jewels", "Combo System", "Daily Challenges"]
    },
    {
        id: "zombie-runner",
        title: "Zombie Runner",
        category: "Action",
        subCategory: "Runner",
        description: "Run through a zombie apocalypse in this thrilling endless runner. Collect supplies and avoid the undead to survive.",
        rating: 4.6,
        difficulty: "medium",
        playCount: 200000,
        releaseDate: "2023-12-30",
        image: "https://img.cdn.famobi.com/portal/html5games/images/tmp/ZombieRunnerTeaser.jpg",
        url: "https://play.famobi.com/zombie-runner",
        tags: ["zombies", "runner", "action", "survival"],
        features: ["Character Upgrades", "Weapon System", "Survival Mode"]
    },
    {
        id: "pixel-art",
        title: "Pixel Art",
        category: "Casual",
        subCategory: "Art",
        description: "Create beautiful pixel art in this relaxing coloring game. Choose from various templates or create your own designs.",
        rating: 4.4,
        difficulty: "easy",
        playCount: 175000,
        releaseDate: "2024-01-05",
        image: "https://img.cdn.famobi.com/portal/html5games/images/tmp/PixelArtTeaser.jpg",
        url: "https://play.famobi.com/pixel-art",
        tags: ["art", "pixel", "coloring", "creative"],
        features: ["Template Gallery", "Color Palette", "Save & Share"]
    },
    {
        id: "ninja-slice",
        title: "Ninja Slice",
        category: "Action",
        subCategory: "Arcade",
        description: "Slice through fruits and objects in this fast-paced arcade game. Test your reflexes and timing to achieve high scores.",
        rating: 4.5,
        difficulty: "medium",
        playCount: 190000,
        releaseDate: "2024-01-10",
        image: "https://img.cdn.famobi.com/portal/html5games/images/tmp/NinjaSliceTeaser.jpg",
        url: "https://play.famobi.com/ninja-slice",
        tags: ["ninja", "slicing", "arcade", "reflexes"],
        features: ["Combo System", "Special Items", "Global Rankings"]
    },
    {
        id: "farm-escape",
        title: "Farm Escape",
        category: "Puzzle",
        subCategory: "Escape",
        description: "Help the farm animals escape from their pens in this challenging puzzle game. Use logic and strategy to free all animals.",
        rating: 4.3,
        difficulty: "medium",
        playCount: 165000,
        releaseDate: "2024-01-15",
        image: "https://img.cdn.famobi.com/portal/html5games/images/tmp/FarmEscapeTeaser.jpg",
        url: "https://play.famobi.com/farm-escape",
        tags: ["farm", "escape", "puzzle", "animals"],
        features: ["Multiple Levels", "Hint System", "Achievement System"]
    },
    {
        id: "color-sort",
        title: "Color Sort",
        category: "Puzzle",
        subCategory: "Sorting",
        description: "Sort colored liquids into matching tubes in this relaxing puzzle game. Use strategy to complete each level with minimal moves.",
        rating: 4.6,
        difficulty: "medium",
        playCount: 180000,
        releaseDate: "2024-01-20",
        image: "https://img.cdn.famobi.com/portal/html5games/images/tmp/ColorSortTeaser.jpg",
        url: "https://play.famobi.com/color-sort",
        tags: ["colors", "sorting", "puzzle", "relaxing"],
        features: ["Undo Move", "Hint System", "Level Editor"]
    },
    {
        id: "block-puzzle",
        title: "Block Puzzle",
        category: "Puzzle",
        subCategory: "Classic",
        description: "Arrange falling blocks to create complete lines in this classic puzzle game. Test your spatial awareness and planning skills.",
        rating: 4.4,
        difficulty: "medium",
        playCount: 170000,
        releaseDate: "2024-01-25",
        image: "https://img.cdn.famobi.com/portal/html5games/images/tmp/BlockPuzzleTeaser.jpg",
        url: "https://play.famobi.com/block-puzzle",
        tags: ["blocks", "puzzle", "classic", "strategy"],
        features: ["Next Piece Preview", "Hold Piece", "Score System"]
    },
    {
        id: "space-adventure",
        title: "Space Adventure",
        category: "Action",
        subCategory: "Adventure",
        description: "Explore the vast universe in this exciting space adventure game. Discover new planets, encounter aliens, and complete missions.",
        rating: 4.7,
        difficulty: "medium",
        playCount: 185000,
        releaseDate: "2024-02-01",
        image: "https://img.cdn.famobi.com/portal/html5games/images/tmp/SpaceAdventureTeaser.jpg",
        url: "https://play.famobi.com/space-adventure",
        tags: ["space", "adventure", "exploration", "action"],
        features: ["Multiple Planets", "Spacecraft Upgrades", "Mission System"]
    },
    {
        id: "dragon-tales",
        title: "Dragon Tales",
        category: "Adventure",
        subCategory: "Fantasy",
        description: "Raise and train your own dragon in this magical adventure game. Explore mystical lands and complete epic quests.",
        rating: 4.6,
        difficulty: "easy",
        playCount: 195000,
        releaseDate: "2024-02-05",
        image: "https://img.cdn.famobi.com/portal/html5games/images/tmp/DragonTalesTeaser.jpg",
        url: "https://play.famobi.com/dragon-tales",
        tags: ["dragon", "fantasy", "adventure", "raising"],
        features: ["Dragon Training", "Quest System", "Customization"]
    },
    {
        id: "pirate-treasure",
        title: "Pirate Treasure",
        category: "Adventure",
        subCategory: "Pirate",
        description: "Embark on a thrilling pirate adventure to find hidden treasures. Navigate through dangerous waters and face rival pirates.",
        rating: 4.5,
        difficulty: "medium",
        playCount: 175000,
        releaseDate: "2024-02-10",
        image: "https://img.cdn.famobi.com/portal/html5games/images/tmp/PirateTreasureTeaser.jpg",
        url: "https://play.famobi.com/pirate-treasure",
        tags: ["pirate", "treasure", "adventure", "exploration"],
        features: ["Ship Upgrades", "Treasure Maps", "Combat System"]
    },
    {
        id: "jungle-escape",
        title: "Jungle Escape",
        category: "Action",
        subCategory: "Adventure",
        description: "Survive in the dangerous jungle environment. Find resources, craft tools, and escape from wild animals.",
        rating: 4.4,
        difficulty: "hard",
        playCount: 165000,
        releaseDate: "2024-02-15",
        image: "https://img.cdn.famobi.com/portal/html5games/images/tmp/JungleEscapeTeaser.jpg",
        url: "https://play.famobi.com/jungle-escape",
        tags: ["jungle", "survival", "adventure", "crafting"],
        features: ["Crafting System", "Day/Night Cycle", "Wildlife AI"]
    },
    {
        id: "robot-builder",
        title: "Robot Builder",
        category: "Simulation",
        subCategory: "Building",
        description: "Design and build your own robots in this creative simulation game. Test them in various challenges and competitions.",
        rating: 4.6,
        difficulty: "medium",
        playCount: 180000,
        releaseDate: "2024-02-20",
        image: "https://img.cdn.famobi.com/portal/html5games/images/tmp/RobotBuilderTeaser.jpg",
        url: "https://play.famobi.com/robot-builder",
        tags: ["robots", "building", "simulation", "creative"],
        features: ["Robot Customization", "Physics Engine", "Competition Mode"]
    },
    {
        id: "time-traveler",
        title: "Time Traveler",
        category: "Adventure",
        subCategory: "Time Travel",
        description: "Travel through different time periods in this exciting adventure game. Solve historical puzzles and change the course of history.",
        rating: 4.7,
        difficulty: "medium",
        playCount: 190000,
        releaseDate: "2024-02-25",
        image: "https://img.cdn.famobi.com/portal/html5games/images/tmp/TimeTravelerTeaser.jpg",
        url: "https://play.famobi.com/time-traveler",
        tags: ["time travel", "history", "adventure", "puzzle"],
        features: ["Multiple Eras", "Historical Events", "Time Paradoxes"]
    },
    {
        id: "magic-school",
        title: "Magic School",
        category: "Simulation",
        subCategory: "Education",
        description: "Attend a magical school and learn various spells and potions. Complete magical challenges and become a powerful wizard.",
        rating: 4.5,
        difficulty: "easy",
        playCount: 200000,
        releaseDate: "2024-03-01",
        image: "https://img.cdn.famobi.com/portal/html5games/images/tmp/MagicSchoolTeaser.jpg",
        url: "https://play.famobi.com/magic-school",
        tags: ["magic", "school", "simulation", "education"],
        features: ["Spell Learning", "Potion Making", "House System"]
    },
    {
        id: "underwater-city",
        title: "Underwater City",
        category: "Simulation",
        subCategory: "City Building",
        description: "Build and manage an underwater city in this unique simulation game. Create sustainable habitats and explore the ocean depths.",
        rating: 4.6,
        difficulty: "medium",
        playCount: 185000,
        releaseDate: "2024-03-05",
        image: "https://img.cdn.famobi.com/portal/html5games/images/tmp/UnderwaterCityTeaser.jpg",
        url: "https://play.famobi.com/underwater-city",
        tags: ["underwater", "city building", "simulation", "management"],
        features: ["Resource Management", "Sea Life", "City Planning"]
    },
    {
        id: "ghost-hunter",
        title: "Ghost Hunter",
        category: "Action",
        subCategory: "Horror",
        description: "Hunt ghosts in haunted locations using special equipment. Capture different types of spirits and solve supernatural mysteries.",
        rating: 4.5,
        difficulty: "medium",
        playCount: 175000,
        releaseDate: "2024-03-10",
        image: "https://img.cdn.famobi.com/portal/html5games/images/tmp/GhostHunterTeaser.jpg",
        url: "https://play.famobi.com/ghost-hunter",
        tags: ["ghosts", "horror", "action", "mystery"],
        features: ["Ghost Types", "Equipment Upgrades", "Investigation System"]
    },
    {
        id: "dinosaur-park",
        title: "Dinosaur Park",
        category: "Simulation",
        subCategory: "Management",
        description: "Build and manage your own dinosaur theme park. Breed dinosaurs, create attractions, and keep visitors safe.",
        rating: 4.7,
        difficulty: "medium",
        playCount: 210000,
        releaseDate: "2024-03-15",
        image: "https://img.cdn.famobi.com/portal/html5games/images/tmp/DinosaurParkTeaser.jpg",
        url: "https://play.famobi.com/dinosaur-park",
        tags: ["dinosaurs", "park management", "simulation", "strategy"],
        features: ["Dinosaur Breeding", "Park Design", "Visitor Management"]
    },
    {
        id: "ninja-training",
        title: "Ninja Training",
        category: "Action",
        subCategory: "Martial Arts",
        description: "Train to become a master ninja in this action-packed game. Learn various techniques and complete challenging missions.",
        rating: 4.6,
        difficulty: "hard",
        playCount: 195000,
        releaseDate: "2024-03-20",
        image: "https://img.cdn.famobi.com/portal/html5games/images/tmp/NinjaTrainingTeaser.jpg",
        url: "https://play.famobi.com/ninja-training",
        tags: ["ninja", "martial arts", "action", "training"],
        features: ["Combat System", "Skill Tree", "Mission System"]
    },
    {
        id: "robot-wars",
        title: "Robot Wars",
        category: "Action",
        subCategory: "Combat",
        description: "Build and battle with custom robots in this exciting combat game. Upgrade your robots and compete in tournaments.",
        rating: 4.5,
        difficulty: "medium",
        playCount: 180000,
        releaseDate: "2024-03-25",
        image: "https://img.cdn.famobi.com/portal/html5games/images/tmp/RobotWarsTeaser.jpg",
        url: "https://play.famobi.com/robot-wars",
        tags: ["robots", "combat", "action", "customization"],
        features: ["Robot Building", "Battle System", "Tournament Mode"]
    },
    {
        id: "zoo-manager",
        title: "Zoo Manager",
        category: "Simulation",
        subCategory: "Management",
        description: "Run your own zoo in this detailed management simulation. Care for animals, attract visitors, and expand your facilities.",
        rating: 4.6,
        difficulty: "medium",
        playCount: 190000,
        releaseDate: "2024-04-01",
        image: "https://img.cdn.famobi.com/portal/html5games/images/tmp/ZooManagerTeaser.jpg",
        url: "https://play.famobi.com/zoo-manager",
        tags: ["zoo", "management", "simulation", "animals"],
        features: ["Animal Care", "Visitor Management", "Facility Planning"]
    },
    {
        id: "space-colony",
        title: "Space Colony",
        category: "Simulation",
        subCategory: "Space",
        description: "Build and manage a colony on a distant planet. Handle resources, maintain life support, and expand your settlement.",
        rating: 4.7,
        difficulty: "hard",
        playCount: 185000,
        releaseDate: "2024-04-05",
        image: "https://img.cdn.famobi.com/portal/html5games/images/tmp/SpaceColonyTeaser.jpg",
        url: "https://play.famobi.com/space-colony",
        tags: ["space", "colony", "simulation", "management"],
        features: ["Resource Management", "Colonist Care", "Base Building"]
    },
    {
        id: "pirate-ship",
        title: "Pirate Ship",
        category: "Simulation",
        subCategory: "Pirate",
        description: "Manage your own pirate ship in this detailed simulation game. Recruit crew members, upgrade your ship, and hunt for treasure.",
        rating: 4.5,
        difficulty: "medium",
        playCount: 175000,
        releaseDate: "2024-04-10",
        image: "https://img.cdn.famobi.com/portal/html5games/images/tmp/PirateShipTeaser.jpg",
        url: "https://play.famobi.com/pirate-ship",
        tags: ["pirate", "ship", "simulation", "management"],
        features: ["Crew Management", "Ship Upgrades", "Treasure Hunting"]
    },
    {
        id: "dragon-breeder",
        title: "Dragon Breeder",
        category: "Simulation",
        subCategory: "Fantasy",
        description: "Breed and raise dragons in this magical simulation game. Create unique dragon species and train them for various purposes.",
        rating: 4.6,
        difficulty: "medium",
        playCount: 195000,
        releaseDate: "2024-04-15",
        image: "https://img.cdn.famobi.com/portal/html5games/images/tmp/DragonBreederTeaser.jpg",
        url: "https://play.famobi.com/dragon-breeder",
        tags: ["dragons", "breeding", "simulation", "fantasy"],
        features: ["Breeding System", "Dragon Training", "Species Creation"]
    },
    {
        id: "robot-factory",
        title: "Robot Factory",
        category: "Simulation",
        subCategory: "Manufacturing",
        description: "Run your own robot manufacturing factory in this detailed simulation game. Design robots, manage production, and fulfill orders.",
        rating: 4.5,
        difficulty: "medium",
        playCount: 180000,
        releaseDate: "2024-04-20",
        image: "https://img.cdn.famobi.com/portal/html5games/images/tmp/RobotFactoryTeaser.jpg",
        url: "https://play.famobi.com/robot-factory",
        tags: ["robots", "factory", "simulation", "management"],
        features: ["Production Line", "Robot Design", "Order Management"]
    },
    {
        id: "time-management",
        title: "Time Management",
        category: "Simulation",
        subCategory: "Business",
        description: "Manage various businesses across different time periods in this challenging simulation game. Make strategic decisions and grow your empire.",
        rating: 4.6,
        difficulty: "hard",
        playCount: 190000,
        releaseDate: "2024-04-25",
        image: "https://img.cdn.famobi.com/portal/html5games/images/tmp/TimeManagementTeaser.jpg",
        url: "https://play.famobi.com/time-management",
        tags: ["business", "management", "simulation", "strategy"],
        features: ["Multiple Businesses", "Time Periods", "Decision Making"]
    },
    {
        id: "space-mining",
        title: "Space Mining",
        category: "Simulation",
        subCategory: "Space",
        description: "Mine valuable resources from asteroids and planets in this space simulation game. Upgrade your equipment and expand your operations.",
        rating: 4.5,
        difficulty: "medium",
        playCount: 185000,
        releaseDate: "2024-05-01",
        image: "https://img.cdn.famobi.com/portal/html5games/images/tmp/SpaceMiningTeaser.jpg",
        url: "https://play.famobi.com/space-mining",
        tags: ["space", "mining", "simulation", "resource"],
        features: ["Mining Equipment", "Resource Management", "Space Travel"]
    },
    {
        id: "pirate-island",
        title: "Pirate Island",
        category: "Simulation",
        subCategory: "Pirate",
        description: "Build and manage your own pirate island in this detailed simulation game. Create defenses, train pirates, and defend against attacks.",
        rating: 4.6,
        difficulty: "medium",
        playCount: 175000,
        releaseDate: "2024-05-05",
        image: "https://img.cdn.famobi.com/portal/html5games/images/tmp/PirateIslandTeaser.jpg",
        url: "https://play.famobi.com/pirate-island",
        tags: ["pirate", "island", "simulation", "defense"],
        features: ["Island Building", "Pirate Training", "Defense System"]
    },
    {
        id: "space-explorer",
        title: "Space Explorer",
        category: "Action",
        subCategory: "Adventure",
        description: "Explore distant galaxies and discover new worlds in this epic space adventure. Encounter alien civilizations and uncover cosmic mysteries.",
        rating: 4.7,
        difficulty: "medium",
        playCount: 190000,
        releaseDate: "2024-05-10",
        image: "https://img.cdn.famobi.com/portal/html5games/images/tmp/SpaceExplorerTeaser.jpg",
        url: "https://play.famobi.com/space-explorer",
        tags: ["space", "exploration", "adventure", "discovery"],
        features: ["Procedural Generation", "Alien Encounters", "Ship Customization"]
    },
    {
        id: "dragon-quest",
        title: "Dragon Quest",
        category: "Adventure",
        subCategory: "Fantasy",
        description: "Embark on an epic quest to save the dragon kingdom. Battle fearsome enemies, collect magical items, and become a legendary dragon rider.",
        rating: 4.6,
        difficulty: "medium",
        playCount: 185000,
        releaseDate: "2024-05-15",
        image: "https://img.cdn.famobi.com/portal/html5games/images/tmp/DragonQuestTeaser.jpg",
        url: "https://play.famobi.com/dragon-quest",
        tags: ["dragon", "fantasy", "quest", "rpg"],
        features: ["Dragon Riding", "Combat System", "Quest System"]
    },
    {
        id: "robot-city",
        title: "Robot City",
        category: "Simulation",
        subCategory: "City Building",
        description: "Build and manage a futuristic city populated by robots. Create efficient systems and maintain harmony in this mechanical metropolis.",
        rating: 4.5,
        difficulty: "medium",
        playCount: 180000,
        releaseDate: "2024-05-20",
        image: "https://img.cdn.famobi.com/portal/html5games/images/tmp/RobotCityTeaser.jpg",
        url: "https://play.famobi.com/robot-city",
        tags: ["robots", "city building", "simulation", "futuristic"],
        features: ["City Planning", "Robot Management", "Resource System"]
    },
    {
        id: "time-master",
        title: "Time Master",
        category: "Puzzle",
        subCategory: "Time Travel",
        description: "Manipulate time to solve complex puzzles. Rewind, fast forward, and create time loops to achieve your objectives.",
        rating: 4.7,
        difficulty: "hard",
        playCount: 170000,
        releaseDate: "2024-05-25",
        image: "https://img.cdn.famobi.com/portal/html5games/images/tmp/TimeMasterTeaser.jpg",
        url: "https://play.famobi.com/time-master",
        tags: ["time travel", "puzzle", "logic", "strategy"],
        features: ["Time Manipulation", "Multiple Solutions", "Level Editor"]
    },
    {
        id: "magic-garden",
        title: "Magic Garden",
        category: "Simulation",
        subCategory: "Fantasy",
        description: "Grow magical plants and create enchanted gardens. Discover rare species and create powerful potions from your harvest.",
        rating: 4.4,
        difficulty: "easy",
        playCount: 195000,
        releaseDate: "2024-06-01",
        image: "https://img.cdn.famobi.com/portal/html5games/images/tmp/MagicGardenTeaser.jpg",
        url: "https://play.famobi.com/magic-garden",
        tags: ["garden", "magic", "simulation", "relaxing"],
        features: ["Plant Breeding", "Potion Making", "Garden Design"]
    },
    {
        id: "underwater-quest",
        title: "Underwater Quest",
        category: "Adventure",
        subCategory: "Ocean",
        description: "Explore the depths of the ocean in this underwater adventure. Discover ancient ruins, encounter sea creatures, and uncover hidden treasures.",
        rating: 4.6,
        difficulty: "medium",
        playCount: 185000,
        releaseDate: "2024-06-05",
        image: "https://img.cdn.famobi.com/portal/html5games/images/tmp/UnderwaterQuestTeaser.jpg",
        url: "https://play.famobi.com/underwater-quest",
        tags: ["ocean", "adventure", "exploration", "underwater"],
        features: ["Diving System", "Sea Life", "Treasure Hunting"]
    },
    {
        id: "ghost-town",
        title: "Ghost Town",
        category: "Action",
        subCategory: "Horror",
        description: "Survive in a haunted town filled with supernatural entities. Solve mysteries, avoid ghosts, and uncover the town's dark secrets.",
        rating: 4.5,
        difficulty: "hard",
        playCount: 175000,
        releaseDate: "2024-06-10",
        image: "https://img.cdn.famobi.com/portal/html5games/images/tmp/GhostTownTeaser.jpg",
        url: "https://play.famobi.com/ghost-town",
        tags: ["ghosts", "horror", "survival", "mystery"],
        features: ["Stealth System", "Ghost Types", "Investigation"]
    },
    {
        id: "dino-hunter",
        title: "Dino Hunter",
        category: "Action",
        subCategory: "Adventure",
        description: "Hunt dinosaurs in this thrilling adventure game. Track different species, use various weapons, and survive in prehistoric environments.",
        rating: 4.6,
        difficulty: "medium",
        playCount: 190000,
        releaseDate: "2024-06-15",
        image: "https://img.cdn.famobi.com/portal/html5games/images/tmp/DinoHunterTeaser.jpg",
        url: "https://play.famobi.com/dino-hunter",
        tags: ["dinosaurs", "hunting", "adventure", "action"],
        features: ["Weapon System", "Tracking", "Environment System"]
    },
    {
        id: "ninja-empire",
        title: "Ninja Empire",
        category: "Action",
        subCategory: "Martial Arts",
        description: "Build your ninja empire and train the next generation of warriors. Manage resources, expand territory, and defend against rival clans.",
        rating: 4.7,
        difficulty: "hard",
        playCount: 180000,
        releaseDate: "2024-06-20",
        image: "https://img.cdn.famobi.com/portal/html5games/images/tmp/NinjaEmpireTeaser.jpg",
        url: "https://play.famobi.com/ninja-empire",
        tags: ["ninja", "empire", "strategy", "martial arts"],
        features: ["Clan Management", "Combat System", "Territory Control"]
    },
    {
        id: "robot-racing",
        title: "Robot Racing",
        category: "Action",
        subCategory: "Racing",
        description: "Race custom-built robots through futuristic tracks. Upgrade your robot's abilities and compete in high-stakes tournaments.",
        rating: 4.5,
        difficulty: "medium",
        playCount: 195000,
        releaseDate: "2024-06-25",
        image: "https://img.cdn.famobi.com/portal/html5games/images/tmp/RobotRacingTeaser.jpg",
        url: "https://play.famobi.com/robot-racing",
        tags: ["robots", "racing", "action", "customization"],
        features: ["Robot Building", "Track Editor", "Tournament System"]
    },
    {
        id: "zoo-tycoon",
        title: "Zoo Tycoon",
        category: "Simulation",
        subCategory: "Management",
        description: "Build and manage the ultimate zoo. Care for exotic animals, create habitats, and provide unforgettable experiences for visitors.",
        rating: 4.6,
        difficulty: "medium",
        playCount: 200000,
        releaseDate: "2024-07-01",
        image: "https://img.cdn.famobi.com/portal/html5games/images/tmp/ZooTycoonTeaser.jpg",
        url: "https://play.famobi.com/zoo-tycoon",
        tags: ["zoo", "management", "simulation", "animals"],
        features: ["Animal Care", "Habitat Design", "Visitor Management"]
    },
    {
        id: "space-defense",
        title: "Space Defense",
        category: "Action",
        subCategory: "Strategy",
        description: "Defend your space station from alien invasions. Build defenses, manage resources, and coordinate your fleet in epic space battles.",
        rating: 4.7,
        difficulty: "hard",
        playCount: 185000,
        releaseDate: "2024-07-05",
        image: "https://img.cdn.famobi.com/portal/html5games/images/tmp/SpaceDefenseTeaser.jpg",
        url: "https://play.famobi.com/space-defense",
        tags: ["space", "defense", "strategy", "action"],
        features: ["Tower Defense", "Fleet Management", "Resource System"]
    },
    {
        id: "pirate-legend",
        title: "Pirate Legend",
        category: "Action",
        subCategory: "Pirate",
        description: "Rise to become a legendary pirate captain. Build your fleet, conquer territories, and amass great wealth through daring adventures.",
        rating: 4.6,
        difficulty: "medium",
        playCount: 190000,
        releaseDate: "2024-07-10",
        image: "https://img.cdn.famobi.com/portal/html5games/images/tmp/PirateLegendTeaser.jpg",
        url: "https://play.famobi.com/pirate-legend",
        tags: ["pirate", "action", "adventure", "strategy"],
        features: ["Fleet Management", "Combat System", "Territory Control"]
    },
    {
        id: "dragon-realm",
        title: "Dragon Realm",
        category: "Simulation",
        subCategory: "Fantasy",
        description: "Create and manage your own dragon sanctuary. Breed rare dragons, train them, and protect your realm from threats.",
        rating: 4.7,
        difficulty: "medium",
        playCount: 195000,
        releaseDate: "2024-07-15",
        image: "https://img.cdn.famobi.com/portal/html5games/images/tmp/DragonRealmTeaser.jpg",
        url: "https://play.famobi.com/dragon-realm",
        tags: ["dragons", "fantasy", "simulation", "management"],
        features: ["Dragon Breeding", "Sanctuary Building", "Combat System"]
    },
    {
        id: "robot-factory-2",
        title: "Robot Factory 2",
        category: "Simulation",
        subCategory: "Manufacturing",
        description: "Expand your robot manufacturing empire. Design new robot models, optimize production lines, and meet growing market demands.",
        rating: 4.5,
        difficulty: "medium",
        playCount: 180000,
        releaseDate: "2024-07-20",
        image: "https://img.cdn.famobi.com/portal/html5games/images/tmp/RobotFactory2Teaser.jpg",
        url: "https://play.famobi.com/robot-factory-2",
        tags: ["robots", "factory", "simulation", "management"],
        features: ["Production System", "Robot Design", "Market System"]
    },
    {
        id: "time-empire",
        title: "Time Empire",
        category: "Simulation",
        subCategory: "Business",
        description: "Build a business empire across different time periods. Make strategic decisions, adapt to historical changes, and create lasting legacies.",
        rating: 4.6,
        difficulty: "hard",
        playCount: 185000,
        releaseDate: "2024-07-25",
        image: "https://img.cdn.famobi.com/portal/html5games/images/tmp/TimeEmpireTeaser.jpg",
        url: "https://play.famobi.com/time-empire",
        tags: ["business", "time travel", "simulation", "strategy"],
        features: ["Historical Events", "Business Management", "Time Periods"]
    },
    {
        id: "space-mining-2",
        title: "Space Mining 2",
        category: "Simulation",
        subCategory: "Space",
        description: "Expand your space mining operations across the galaxy. Discover new resources, upgrade equipment, and establish mining colonies.",
        rating: 4.5,
        difficulty: "medium",
        playCount: 190000,
        releaseDate: "2024-08-01",
        image: "https://img.cdn.famobi.com/portal/html5games/images/tmp/SpaceMining2Teaser.jpg",
        url: "https://play.famobi.com/space-mining-2",
        tags: ["space", "mining", "simulation", "resource"],
        features: ["Mining System", "Colony Management", "Resource Trading"]
    },
    {
        id: "pirate-fortress",
        title: "Pirate Fortress",
        category: "Simulation",
        subCategory: "Pirate",
        description: "Build and defend your pirate fortress. Create impenetrable defenses, train your crew, and repel enemy attacks.",
        rating: 4.6,
        difficulty: "medium",
        playCount: 175000,
        releaseDate: "2024-08-05",
        image: "https://img.cdn.famobi.com/portal/html5games/images/tmp/PirateFortressTeaser.jpg",
        url: "https://play.famobi.com/pirate-fortress",
        tags: ["pirate", "defense", "simulation", "strategy"],
        features: ["Fortress Building", "Defense System", "Crew Management"]
    }
].map(game => ({
    ...game,
    category: autoCategorizegame(game)
}));

// 处理未分类游戏
function validateGameCategories(games) {
    return games.map(game => {
        if (!game.category) {
            game.category = autoCategorizegame(game);
        }
        return game;
    });
}

// 游戏难度定义
const difficulties = {
    easy: '简单',
    medium: '中等',
    hard: '困难'
};

// 将数据暴露为全局变量
window.gameData = validateGameCategories(gameData);
window.categories = categories;
window.difficulties = difficulties;
